@startuml
state f <<fork>>
state j <<join>>
[*] --> f
f --> Branch0Start : start0
Branch0Start --> Branch0Mid
Branch0Mid --> Branch0End
Branch0End --> j : end0
f --> Branch1Start : start1
Branch1Start --> Branch1Mid
Branch1Mid --> Branch1End
Branch1End --> j : end1
f --> Branch2Start : start2
Branch2Start --> Branch2Mid
Branch2Mid --> Branch2End
Branch2End --> j : end2
f --> Branch3Start : start3
Branch3Start --> Branch3Mid
Branch3Mid --> Branch3End
Branch3End --> j : end3
f --> Branch4Start : start4
Branch4Start --> Branch4Mid
Branch4Mid --> Branch4End
Branch4End --> j : end4
j --> [*]
@enduml
