@startuml
state Machine1 {
  [*] --> A
  A --> [*]
}

state Machine2 {
  [*] --> B
  B --> [*]
}

state Machine3 {
  [*] --> C
  C --> [*]
}

[*] --> Machine1
Machine1 --> Machine2
Machine2 --> Machine3
Machine3 --> [*]
@enduml
