@startuml
state f <<fork>>
state j <<join>>
[*] --> f
f --> Branch0Start : start0
Branch0Start --> Branch0Mid
Branch0Mid --> Branch0End
Branch0End --> j : end0
f --> Branch1Start : start1
Branch1Start --> Branch1Mid
Branch1Mid --> Branch1End
Branch1End --> j : end1
f --> Branch2Start : start2
Branch2Start --> Branch2Mid
Branch2Mid --> Branch2End
Branch2End --> j : end2
j --> [*]
@enduml
