@startuml
state Root {
  state Level1 {
    state Level2 {
      state Level3 {
        state Level4 {
          [*] --> Leaf
          Leaf --> [*]
        }
        [*] --> Level4
        Level4 --> [*]
      }
      [*] --> Level3
      Level3 --> [*]
    }
    [*] --> Level2
    Level2 --> [*]
  }
  [*] --> Level1
  Level1 --> [*]
}
[*] --> Root
Root --> [*]
@enduml
