@startuml
state Concurrent {
  [*] --> R0S0
  R0S0 --> R0S1 : step0
  R0S1 --> R0S2 : step1
  R0S2 --> [*]
  --
  [*] --> R1S0
  R1S0 --> R1S1 : step0
  R1S1 --> R1S2 : step1
  R1S2 --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
