@startuml
state fork1 <<fork>>
state join1 <<join>>

[*] --> fork1
fork1 --> T1
fork1 --> T2
fork1 --> T3
T1 --> join1 : ok
T1 --> Compensate : fail
T2 --> join1 : ok
T2 --> Compensate : fail
T3 --> join1 : ok
T3 --> Compensate : fail
join1 --> Done
Compensate --> [*]
Done --> [*]
@enduml
