@startuml
state Composite {
  state H <<history>>
  [*] --> H
  H --> Active
  Active --> Paused
  Paused --> Active
  --
  [*] --> Logging
  Logging --> [*]
}
[*] --> Composite
Composite --> Done
Done --> [*]
@enduml
