@startuml
[*] --> L1
state L1 {
  [*] --> L2
  state L2 {
    [*] --> L3
    state L3 {
      [*] --> L4
      state L4 {
        [*] --> S
        S --> [*]
      }
      L4 --> [*]
    }
    L3 --> [*]
  }
  L2 --> [*]
}
L1 --> [*]
@enduml
