@startuml
state Outer1 {
  [*] --> IS1
  IS1 --> IS2
  IS2 --> [*]
}
state Outer2 {
  [*] --> IS1
  IS1 --> IS2
  IS2 --> [*]
}
state Outer3 {
  [*] --> IS1
  IS1 --> IS2
  IS2 --> [*]
}
[*] --> Outer1
Outer1 --> Outer2
Outer2 --> Outer3
Outer3 --> [*]
@enduml
