@startuml
state Concurrent {
  state "Region 1" as R1 {
    [*] --> R1A
    R1A --> [*]
  }
  --
  state "Region 2" as R2 {
    [*] --> R2A
    R2A --> [*]
  }
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
