@startuml
state L1 {
  state L2 {
    [*] --> X
    X --> Y
    Y --> [*]
    --
    [*] --> P
    P --> Q
    Q --> [*]
  }
  [*] --> L2
  L2 --> [*]
  --
  [*] --> Z
  Z --> W
  W --> [*]
}
[*] --> L1
L1 --> [*]
@enduml
