@startuml
state Outer {
  state Inner1 {
    [*] --> X
    X --> [*]
    --
    [*] --> Y
    Y --> [*]
  }
  state Inner2 {
    [*] --> P
    P --> Q
    Q --> [*]
    --
    [*] --> R
    R --> [*]
  }
  [*] --> Inner1
  Inner1 --> Inner2
  Inner2 --> [*]
}
[*] --> Outer
Outer --> [*]
@enduml
