@startuml
state Composite {
  [*] --> I1
  I1 --> I2 : step1
  I2 --> I3 : step2
  I3 --> I4 : step3
  I4 --> I5 : step4
  I5 --> I6 : step5
  I6 --> I7 : step6
  I7 --> [*]
}
[*] --> Composite
Composite --> [*]
@enduml
