@startuml
[*] --> S1
S1 --> S2 : event1
S2 --> S3
S3 --> S4 : event3 [guard3] / action3
S4 --> S5 : event4
S5 --> S6
S6 --> S7 : event6 [guard6] / action6
S7 --> S8 : event7
S8 --> S9
S9 --> S10 : event9 [guard9] / action9
S10 --> S11 : event10
S11 --> S12
S12 --> S13 : event12 [guard12] / action12
S13 --> S14 : event13
S14 --> S15
S15 --> S16 : event15 [guard15] / action15
S16 --> S17 : event16
S17 --> S18
S18 --> S19 : event18 [guard18] / action18
S19 --> S20 : event19
S20 --> S21
S21 --> S22 : event21 [guard21] / action21
S22 --> S23 : event22
S23 --> S24
S24 --> S25 : event24 [guard24] / action24
S25 --> S26 : event25
S26 --> S27
S27 --> S28 : event27 [guard27] / action27
S28 --> S29 : event28
S29 --> S30
S30 --> S31 : event30 [guard30] / action30
S31 --> S32 : event31
S32 --> S33
S33 --> S34 : event33 [guard33] / action33
S34 --> S35 : event34
S35 --> S36
S36 --> S37 : event36 [guard36] / action36
S37 --> S38 : event37
S38 --> S39
S39 --> S40 : event39 [guard39] / action39
S40 --> S41 : event40
S41 --> S42
S42 --> [*]
@enduml
