@startuml
state Concurrent {
  [*] --> R0S1
  R0S1 --> R0S2
  R0S2 --> [*]
  --
  [*] --> R1S1
  R1S1 --> R1S2
  R1S2 --> [*]
  --
  [*] --> R2S1
  R2S1 --> R2S2
  R2S2 --> [*]
  --
  [*] --> R3S1
  R3S1 --> R3S2
  R3S2 --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
