@startuml
[*] --> S1
S1 --> S4 : e1
S2 --> S1 : e2
S3 --> S9 : e3
S4 --> S8 : e4
S5 --> S8 : e5
S6 --> S5 : e6
S7 --> S4 : e7
S8 --> S18 : e8
S9 --> S3 : e9
S10 --> S19 : e10
S11 --> S14 : e11
S12 --> S2 : e12
S13 --> S1 : e13
S14 --> S3 : e14
S15 --> S7 : e15
S16 --> S8 : e16
S18 --> S20 : e18
S19 --> S1 : e19
S20 --> S18 : e20
S20 --> [*]
@enduml
