@startuml
state Concurrent {
  [*] --> R0S1
  R0S1 --> [*]
  --
  [*] --> R1S1
  R1S1 --> [*]
  --
  [*] --> R2S1
  R2S1 --> [*]
  --
  [*] --> R3S1
  R3S1 --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
