@startuml
skinparam state {
  BackgroundColor<<composite>> LightYellow
  BorderColor<<composite>> Orange
}
state Composite {
  [*] --> Inner
  Inner --> [*]
}
[*] --> Composite
Composite --> [*]
@enduml
