@startuml
state Concurrent {
  [*] --> R0A
  R0A --> R0B
  R0B --> [*]
  --
  [*] --> R1A
  R1A --> R1B
  R1B --> [*]
  --
  [*] --> R2A
  R2A --> R2B
  R2B --> [*]
  --
  [*] --> R3A
  R3A --> R3B
  R3B --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
