@startuml
state Concurrent {
  [*] --> R0S1
  R0S1 --> R0S2
  R0S2 --> R0S3
  R0S3 --> R0S4
  R0S4 --> [*]
  --
  [*] --> R1S1
  R1S1 --> R1S2
  R1S2 --> R1S3
  R1S3 --> R1S4
  R1S4 --> [*]
  --
  [*] --> R2S1
  R2S1 --> R2S2
  R2S2 --> R2S3
  R2S3 --> R2S4
  R2S4 --> [*]
  --
  [*] --> R3S1
  R3S1 --> R3S2
  R3S2 --> R3S3
  R3S3 --> R3S4
  R3S4 --> [*]
  --
  [*] --> R4S1
  R4S1 --> R4S2
  R4S2 --> R4S3
  R4S3 --> R4S4
  R4S4 --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
