@startuml
[*] --> S1
S1 --> S2 : e1
S2 --> S3 : e2
S3 --> S4 : e3
S4 --> S5 : e4
S5 --> S6 : e5
S6 --> S7 : e6
S7 --> [*]
note right of S1 : State 1 note
note right of S3 : State 3 note
note right of S5 : State 5 note
note right of S7 : State 7 note
@enduml
