@startuml
[*] --> C1
state C1 {
  [*] --> CS1
  CS1 --> [*]
}
state C2 {
  [*] --> CS2
  CS2 --> [*]
}
state C3 {
  [*] --> CS3
  CS3 --> [*]
}
state C4 {
  [*] --> CS4
  CS4 --> [*]
}
state C5 {
  [*] --> CS5
  CS5 --> [*]
}
state C6 {
  [*] --> CS6
  CS6 --> [*]
}
C1 --> C2
C2 --> C3
C3 --> C4
C4 --> C5
C5 --> C6
C6 --> [*]
@enduml
