@startuml
state Outer {
  state Inner {
    [*] --> X
    X --> [*]
    --
    [*] --> Y
    Y --> [*]
  }
  [*] --> Inner
  Inner --> [*]
  --
  [*] --> Z
  Z --> [*]
}
[*] --> Outer
Outer --> [*]
@enduml
