@startuml
state Composite {
  state ep0 <<entryPoint>>
  state ep1 <<entryPoint>>
  state xp0 <<exitPoint>>
  ep0 --> State0
  ep1 --> State1
  State0 --> xp0
  State1 --> xp0
}
[*] --> Composite
Composite --> [*]
@enduml
