@startuml
state c <<choice>>
[*] --> Start
Start --> c
c --> End0 : [path0]
c --> End1 : [path1]
c --> End2 : [path2]
c --> End3 : [path3]
c --> End4 : [path4]
End0 --> [*]
End1 --> [*]
End2 --> [*]
End3 --> [*]
End4 --> [*]
@enduml
