@startuml
state Concurrent {
  [*] --> CR0A
  CR0A --> CR0B
  CR0B --> [*]
  --
  [*] --> CR1A
  CR1A --> CR1B
  CR1B --> [*]
  --
  [*] --> CR2A
  CR2A --> CR2B
  CR2B --> [*]
  --
  [*] --> CR3A
  CR3A --> CR3B
  CR3B --> [*]
  --
  [*] --> CR4A
  CR4A --> CR4B
  CR4B --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
