@startuml
[*] --> A
state A {
  [*] --> A1
  A1 --> A2
  A2 --> [*]
}
state B {
  [*] --> B1
  B1 --> [*]
}
state C {
  [*] --> C1
  C1 --> C2
  C2 --> C3
  C3 --> [*]
}
A --> B
B --> C
C --> [*]
@enduml
