@startuml
[*] --> S0
S0 --> S1 : e01
S0 --> S2 : e02
S0 --> S3 : e03
S1 --> S0 : e10
S1 --> S2 : e12
S1 --> S3 : e13
S2 --> S0 : e20
S2 --> S1 : e21
S2 --> S3 : e23
S3 --> S0 : e30
S3 --> S1 : e31
S3 --> S2 : e32
S3 --> [*]
@enduml
