@startuml
state Concurrent {
  [*] --> A
  A --> [*]
  --
  [*] --> B
  B --> [*]
}

state fork1 <<fork>>
state join1 <<join>>

[*] --> Concurrent
Concurrent --> fork1
fork1 --> C
fork1 --> D
C --> join1
D --> join1
join1 --> [*]
@enduml
