@startuml
state Concurrent {
  [*] --> R0S0
  R0S0 --> R0S1 : step0
  R0S1 --> [*]
  --
  [*] --> R1S0
  R1S0 --> R1S1 : step0
  R1S1 --> [*]
  --
  [*] --> R2S0
  R2S0 --> R2S1 : step0
  R2S1 --> [*]
  --
  [*] --> R3S0
  R3S0 --> R3S1 : step0
  R3S1 --> [*]
}
[*] --> Concurrent
Concurrent --> [*]
@enduml
