@startuml
left to right direction
node "Review Edge" as Edge {
  package "Review Public" as Public {
    [Review API] as Api
  }
  package "Review Private" as Private {
    Ledger as [Review Ledger]
  }
}
Api -right-> Ledger : writes
@enduml
