@startwbs
* Hardware Design
** Schematic
*** Requirements
*** Design
*** Review
** Layout
*** Placement
*** Routing
*** DRC
** Fabrication
*** Gerber
*** Order
*** Assembly
** Testing
*** Continuity
*** Functional
*** EMC

@endwbs
