@startwbs
*[#lightgreen] Root 9
** Node d2 w0
** Node d2 w1
** Node d2 w2
*** Node d3 w0
*** Node d3 w1
*** Node d3 w2
**** Node d4 w0
**** Node d4 w1
**** Node d4 w2
***** Node d5 w0
***** Node d5 w1
***** Node d5 w2
****** Node d6 w0
@endwbs
