@startwbs
*[#lightblue] Project 4
**[#green] Task 0: Done
***[#white] Subtask 0.1
**[#yellow] Task 1: In Progress
**[#red] Task 2: Blocked
**[#white] Task 3: Pending
***[#white] Subtask 3.1
**[#lightblue] Task 4: In Review
**[#green] Task 5: Done
**[#yellow] Task 6: In Progress
***[#white] Subtask 6.1

@endwbs
