@startuml
left to right direction
skinparam packageStyle stack

<style>
classDiagram {
  package {
    title {
      RoundCorner 0
    }
  }
}
</style>

package "Zero Shelf 9411" as ZeroShelf9411 {
}
@enduml
