@startuml
skinparam shadowing false
skinparam sequenceActorBackgroundColor #FF0000|#0000FF
skinparam sequenceParticipantBackgroundColor #00FFFF/#FFC0CB
actor Caller931
participant Worker937
Caller931 -> Worker937 : first pass
Worker937 --> Caller931 : second pass
@enduml
