@startuml
node "Anchor V13D" as DAnchorV13D
NoTe matrix\nV13D“ As Memo.DV13D #LightBlue-LightGreen
artifact "Peer V13D" as DPeerV13D
Memo.DV13D --> DAnchorV13D : ownership
cloud "Late V13D" as DLateV13D
DAnchorV13D --> DPeerV13D : order
@enduml
