@startuml
left to right direction
skinparam topurl https://docs.example/base/
package "API Surface" as systems.api $core <<Facade>> $stable [[guides/api{Guide docs} helper-label]] #AliceBlue {
  class Client
}
package systems.api {
  package NestedDocs [[https://example.com/nested{Nested docs} nested-label]] {
    class Worker
  }
}
Client --> Worker
@enduml
