@startuml

start
if (mode == batch?) then (yes)
  while (items?) is (yes)
    :Process batch item;
  endwhile
elseif (mode == stream?) then (yes)
  repeat
    :Process stream item;
  repeatwhile (streaming?) is (yes)
else (idle)
  :Wait for work;
endif
stop
@enduml
