@startuml
start
group "Group 1" {
  :Group 1 action;
}
group "Group 2" {
  :Group 2 action;
}
group "Group 3" {
  :Group 3 action;
}
group "Group 4" {
  :Group 4 action;
}
group "Group 5" {
  :Group 5 action;
}
stop
@enduml
