@startuml
start
#red:Step 1;
#orange:Step 2;
#yellow:Step 3;
#green:Step 4;
#blue:Step 5;
#purple:Step 6;
#pink:Step 7;
#red:Step 8;
#orange:Step 9;
#yellow:Step 10;
#green:Step 11;
#blue:Step 12;
#purple:Step 13;
#pink:Step 14;
#red:Step 15;
#orange:Step 16;
#yellow:Step 17;
#green:Step 18;
#blue:Step 19;
#purple:Step 20;
#pink:Step 21;
#red:Step 22;
#orange:Step 23;
#yellow:Step 24;
#green:Step 25;
#blue:Step 26;
#purple:Step 27;
#pink:Step 28;
#red:Step 29;
#orange:Step 30;
stop
@enduml
