@startuml
|L1|
start
repeat
  :Try;
repeatwhile (more?)
|L2|
repeat
  :Try;
repeatwhile (more?)
|L3|
repeat
  :Try;
repeatwhile (more?)
|L4|
repeat
  :Try;
repeatwhile (more?)
|L5|
repeat
  :Try;
repeatwhile (more?)
stop
@enduml
