@startuml
start
partition "P1" {
if (p1cond1?) then (yes)
  :P1 inner action;
else (no)
  :P1 alt 1;
endif
}
partition "P2" {
if (p2cond1?) then (yes)
  :P2 inner action;
else (no)
  :P2 alt 1;
endif
}
partition "P3" {
if (p3cond1?) then (yes)
  :P3 inner action;
else (no)
  :P3 alt 1;
endif
}
stop
@enduml
