@startuml

start
repeat
  if (cond1?) then (yes)
    if (cond2?) then (yes)
  :    Action;
    else (no)
      :Alt 2;
    endif
  else (no)
    :Alt 1;
  endif
repeatwhile (more?) is (yes)
stop
@enduml
