@startuml
|Lane1|
start
if (cond 1?) then (b1)
  :Branch 1;
elseif (cond 2?) then (b2)
  |Lane1|
  :Branch 2;
elseif (cond 3?) then (b3)
  |Lane2|
  :Branch 3;
else (default)
  :Default;
endif
stop
@enduml
