@startuml
start
if (L1?) then (yes)
  if (L2?) then (yes)
    repeat
      :Repeat 1;
    repeatwhile (m1?)
    repeat
      :Repeat 2;
    repeatwhile (m2?)
    repeat
      :Repeat 3;
    repeatwhile (m3?)
  else (no)
    :Alt;
  endif
else (no)
  :Alt;
endif
stop
@enduml
