@startuml

start
if (outer?) then (yes)
  switch (val?)
case (1)
    :C1;
case (2)
    :C2;
case (3)
    :C3;
case (4)
    :C4;
case (5)
    :C5;
case (6)
    :C6;
  endswitch
else (no)
  :Alt;
endif
stop
@enduml
