@startuml
start
switch (val?)
case (1)
  if (sub-cond 1?) then (yes)
    :Case 1 yes;
  else (no)
    :Case 1 no;
  endif
case (2)
  if (sub-cond 2?) then (yes)
    :Case 2 yes;
  else (no)
    :Case 2 no;
  endif
endswitch
stop
@enduml
