@startuml

start
partition #lightblue "Setup" {
  :Initialize;
  :Configure;
}
partition #lightyellow "Execute" {
  :Run;
  :Monitor;
}
partition #lightgreen "Cleanup" {
  :Finalize;
  :Dispose;
}
stop
@enduml
