@startuml
start
if (condition 1?) then (yes)
  :Action 1a;
else (no)
  :Action 1b;
endif
if (condition 2?) then (yes)
  :Action 2a;
else (no)
  :Action 2b;
endif
if (condition 3?) then (yes)
  :Action 3a;
else (no)
  :Action 3b;
endif
if (condition 4?) then (yes)
  :Action 4a;
else (no)
  :Action 4b;
endif
if (condition 5?) then (yes)
  :Action 5a;
else (no)
  :Action 5b;
endif
if (condition 6?) then (yes)
  :Action 6a;
else (no)
  :Action 6b;
endif
if (condition 7?) then (yes)
  :Action 7a;
else (no)
  :Action 7b;
endif
if (condition 8?) then (yes)
  :Action 8a;
else (no)
  :Action 8b;
endif
if (condition 9?) then (yes)
  :Action 9a;
else (no)
  :Action 9b;
endif
if (condition 10?) then (yes)
  :Action 10a;
else (no)
  :Action 10b;
endif
stop
@enduml
