@startuml
|L1|
start
while (loop?) is (yes)
  :Work;
endwhile
|L2|
while (loop?) is (yes)
  :Work;
endwhile
|L3|
while (loop?) is (yes)
  :Work;
endwhile
|L4|
while (loop?) is (yes)
  :Work;
endwhile
|L5|
while (loop?) is (yes)
  :Work;
endwhile
stop
@enduml
