@startuml
start
fork
  :Branch 1 start;
  if (b1cond1?) then (yes)
  :Branch 1 work;
  else (no)
    :B1 alt 1;
  endif
fork again
  :Branch 2 start;
  if (b2cond1?) then (yes)
  :Branch 2 work;
  else (no)
    :B2 alt 1;
  endif
end fork
stop
@enduml
