@startuml
start
fork
  :Branch 1 start;
  if (b1cond1?) then (yes)
    if (b1cond2?) then (yes)
  :Branch 1 work;
    else (no)
      :B1 alt 2;
    endif
  else (no)
    :B1 alt 1;
  endif
fork again
  :Branch 2 start;
  if (b2cond1?) then (yes)
    if (b2cond2?) then (yes)
  :Branch 2 work;
    else (no)
      :B2 alt 2;
    endif
  else (no)
    :B2 alt 1;
  endif
fork again
  :Branch 3 start;
  if (b3cond1?) then (yes)
    if (b3cond2?) then (yes)
  :Branch 3 work;
    else (no)
      :B3 alt 2;
    endif
  else (no)
    :B3 alt 1;
  endif
fork again
  :Branch 4 start;
  if (b4cond1?) then (yes)
    if (b4cond2?) then (yes)
  :Branch 4 work;
    else (no)
      :B4 alt 2;
    endif
  else (no)
    :B4 alt 1;
  endif
end fork
stop
@enduml
