@startuml

start
if (outer?) then (yes)
  if (inner?) then (yes)
    :Both true;
  else (no)
    :Outer true inner false;
  endif
else (no)
  if (inner?) then (yes)
    :Outer false inner true;
  else (no)
    :Both false;
  endif
endif
stop
@enduml
