@startuml
start
:Action 1;
:Action 2;
:Action 3;
:Action 4;
:Action 5;
:Action 6;
:Action 7;
:Action 8;
:Action 9;
:Action 10;
:Action 11;
:Action 12;
:Action 13;
:Action 14;
:Action 15;
:Action 16;
:Action 17;
:Action 18;
:Action 19;
:Action 20;
stop
@enduml
