@startuml
start
repeat
  :Repeat 1 body;
repeatwhile (more 1?) is (yes)
repeat
  :Repeat 2 body;
repeatwhile (more 2?) is (yes)
repeat
  :Repeat 3 body;
repeatwhile (more 3?) is (yes)
repeat
  :Repeat 4 body;
repeatwhile (more 4?) is (yes)
stop
@enduml
