@startuml
|SL1|
start
if (go?) then (yes)
  while (loop?) is (yes)
    fork
  |SL1|
  :Branch 1;
fork again
  |SL2|
  :Branch 2;
fork again
  |SL3|
  :Branch 3;
fork again
  |SL1|
  :Branch 4;
end fork
  endwhile
else (no)
  :Skip;
endif
stop
@enduml
