@startuml

title Cache-Aside Pattern
start
:Request data(key);
if (cache hit?) then (yes)
  :Return from cache;
  stop
else (no)
  :Query database;
  if (found?) then (yes)
    fork
      :Store in cache;
    fork again
      :Return to caller;
    end fork
    stop
  else (no)
    :Return null;
    stop
  endif
endif
@enduml
