@startuml
|Lane A|
start
:Action 1;
|Lane B|
:Action 2;
|Lane A|
:Action 3;
|Lane B|
:Action 4;
|Lane A|
:Action 5;
|Lane B|
:Action 6;
|Lane A|
:Action 7;
|Lane B|
:Action 8;
|Lane A|
:Action 9;
|Lane B|
:Action 10;
|Lane A|
:Action 11;
|Lane B|
:Action 12;
|Lane A|
:Action 13;
|Lane B|
:Action 14;
stop
@enduml
