@startuml

start
repeat
  switch (event?)
case (1)
  :Handle 1;
case (2)
  :Handle 2;
case (3)
  :Handle 3;
case (4)
  :Handle 4;
case (5)
  :Handle 5;
  endswitch
repeatwhile (more events?) is (yes)
stop
@enduml
