@startuml
start
while (loop 1?) is (yes)
  :Loop 1 body;
endwhile (done)
while (loop 2?) is (yes)
  :Loop 2 body;
endwhile (done)
while (loop 3?) is (yes)
  :Loop 3 body;
endwhile (done)
while (loop 4?) is (yes)
  :Loop 4 body;
endwhile (done)
while (loop 5?) is (yes)
  :Loop 5 body;
endwhile (done)
stop
@enduml
