@startuml
start
if (condition 1?) then (yes)
  :Action 1;
else (no)
  :Alt 1;
endif
if (condition 2?) then (yes)
  :Action 2;
else (no)
  :Alt 2;
endif
if (condition 3?) then (yes)
  :Action 3;
else (no)
  :Alt 3;
endif
if (condition 4?) then (yes)
  :Action 4;
else (no)
  :Alt 4;
endif
if (condition 5?) then (yes)
  :Action 5;
else (no)
  :Alt 5;
endif
if (condition 6?) then (yes)
  :Action 6;
else (no)
  :Alt 6;
endif
if (condition 7?) then (yes)
  :Action 7;
else (no)
  :Alt 7;
endif
if (condition 8?) then (yes)
  :Action 8;
else (no)
  :Alt 8;
endif
if (condition 9?) then (yes)
  :Action 9;
else (no)
  :Alt 9;
endif
if (condition 10?) then (yes)
  :Action 10;
else (no)
  :Alt 10;
endif
if (condition 11?) then (yes)
  :Action 11;
else (no)
  :Alt 11;
endif
if (condition 12?) then (yes)
  :Action 12;
else (no)
  :Alt 12;
endif
if (condition 13?) then (yes)
  :Action 13;
else (no)
  :Alt 13;
endif
if (condition 14?) then (yes)
  :Action 14;
else (no)
  :Alt 14;
endif
if (condition 15?) then (yes)
  :Action 15;
else (no)
  :Alt 15;
endif
stop
@enduml
