@startuml
start
partition "Partition 1" {
  :Part 1 Action 1;
  :Part 1 Action 2;
}
partition "Partition 2" {
  :Part 2 Action 1;
  :Part 2 Action 2;
}
partition "Partition 3" {
  :Part 3 Action 1;
  :Part 3 Action 2;
}
partition "Partition 4" {
  :Part 4 Action 1;
  :Part 4 Action 2;
}
stop
@enduml
