@startuml
start
if (cond 1?) then (b1)
  :B1 action 1;
  :B1 action 2;
  :B1 action 3;
elseif (cond 2?) then (b2)
  :B2 action 1;
  :B2 action 2;
  :B2 action 3;
elseif (cond 3?) then (b3)
  :B3 action 1;
  :B3 action 2;
  :B3 action 3;
else (default)
  :Default action 1;
  :Default action 2;
  :Default action 3;
endif
stop
@enduml
