@startuml

start
while (outer run?) is (yes)
  if (A?) then (yes)
    if (B?) then (yes)
      break
    else (no)
      :Handle B false;
    endif
  else (no)
    :Handle A false;
  endif
endwhile
stop
@enduml
