@startuml

start
if (A?) then (yes)
  if (B?) then (yes)
    if (C?) then (yes)
      :A and B and C;
    else (no)
      :A and B not C;
    endif
  else (no)
    :A not B;
  endif
else (no)
  if (B?) then (yes)
    :Not A but B;
  else (no)
    :Not A not B;
  endif
endif
stop
@enduml
