@startuml

|Lane A|
start
if (L1?) then (yes)
  if (L2?) then (yes)
    if (L3?) then (yes)
      |Lane B|
      :Deep in lane B;
      |Lane A|
    else (no)
      :L3 false;
    endif
  else (no)
    :L2 false;
  endif
else (no)
  :L1 false;
endif
stop
@enduml
