@startuml
!definelong PERSON_CLASS(name, field1, field2)
class name {
  +field1: String
  +field2: int
  +toString(): String
}
!enddefinelong

PERSON_CLASS(Customer, customerName, customerId)
PERSON_CLASS(Employee, employeeName, employeeId)
Customer --> Employee : managed by
@enduml
