@startuml
!define MY_MACRO

!if %is_defined("MY_MACRO")
note as N1
  MY_MACRO is defined
end note
!endif

!if !%is_defined("MISSING_MACRO")
note as N2
  MISSING_MACRO is not defined
end note
!endif
@enduml
