@startuml
!function $is_positive($n)
  !return $n > 0
!endfunction

!function $is_even($n)
  !return ($n % 2) == 0
!endfunction

!$tests = 6
!$i = 1
!while $i <= $tests
  note as N$i
    $i: positive=$is_positive($i), even=$is_even($i)
  end note
  !$i = $i + 1
!endwhile
@enduml
