@startuml
!procedure $entity($name, $parent)
  class $name extends $parent {
    +id: long
  }
!endprocedure

class BaseEntity {
  +createdAt: Date
  +updatedAt: Date
}
$entity(User, BaseEntity)
$entity(Post, BaseEntity)
$entity(Comment, BaseEntity)
@enduml
