@startuml
!define DEVELOPMENT

!ifdef DEVELOPMENT
skinparam noteBackgroundColor LightGreen
note as N
  DEVELOPMENT mode is active
end note
!else
note as N
  DEVELOPMENT mode is inactive
end note
!endif
Alice -> Bob : development mode test
@enduml
