@startuml
!define DEBUG

!ifdef DEBUG
skinparam noteBackgroundColor LightGreen
note as N
  DEBUG mode is active
end note
!else
note as N
  DEBUG mode is inactive
end note
!endif
Alice -> Bob : debug mode test
@enduml
