@startuml
!define STAGING

!ifdef STAGING
skinparam noteBackgroundColor LightGreen
note as N
  STAGING mode is active
end note
!else
note as N
  STAGING mode is inactive
end note
!endif
Alice -> Bob : staging mode test
@enduml
