@startuml
!define ENV_STAGING

!ifdef ENV_STAGING
skinparam backgroundColor LightBlue
skinparam noteBackgroundColor LightBlue
!endif

title Environment: staging
Alice -> Bob : deployed to staging
@enduml
