@startuml
!$level = 2

!if $level == 1
note as N
  Level 1
end note
!elseif $level == 2
note as N
  Level 2
end note
!elseif $level == 3
note as N
  Level 3
end note
!else
note as N
  Unknown level: $level
end note
!endif
@enduml
