@startuml
!$services = 3
!$i = 1
!while $i <= $services
  participant "Service$i" as S$i
  !$i = $i + 1
!endwhile

Client -> S1 : request
!$i = 1
!while $i < $services
  !$next = $i + 1
  S$i -> S$next : forward
  !$i = $next
!endwhile
S3 --> Client : response
@enduml
