@startuml
!function $add($a, $b)
  !return $a + $b
!endfunction

!function $multiply($a, $b)
  !return $a * $b
!endfunction

!$r1 = $add(3, 4)
!$r2 = $multiply(3, 4)
!$r3 = $add($r1, $r2)

note as N
  add(3,4) = $r1
  multiply(3,4) = $r2
  add($r1,$r2) = $r3
end note
@enduml
