@startuml
skinparam state {
  FontName<<ledger>> Courier New
  FontSize<<ledger>> 21
  FontStyle<<ledger>> bold italic
}
state "Ledger Capsule" as LedgerCapsule <<ledger>> {
  [*] --> DetailedLedger
  state "Detailed Ledger" as DetailedLedger <<ledger>>
  DetailedLedger --> [*]
}
[*] --> LedgerCapsule
LedgerCapsule --> [*]
@enduml
