@startuml
node Target
note as TransparentSolid #transparent
transparent solid body
endnote
note as BackgroundSolid #background
background solid body
endnote
TransparentSolid --> Target
BackgroundSolid --> Target
@enduml
