@startuml
package P1 {
  package P2 {
    package P3 {
      package P4 {
        package P5 {
          class VeryDeep
        }
        class L4
      }
      class L3
    }
    class L2
  }
  class L1
}

@enduml
