@startuml
namespace com.example.ui {
  class View
  class Controller
}
namespace com.example.service {
  class UserService
  class AuthService
}
namespace com.example.data {
  class UserRepo
}
Controller --> UserService
UserService --> UserRepo
AuthService --> UserRepo

@enduml
