@startuml
actor "System 1" <<system>>
actor "System 2" <<system>>
actor "System 3" <<system>>
actor "System 4" <<system>>
usecase UC1
usecase UC2
usecase UC3
usecase UC4
"System 1" --> UC1
"System 2" --> UC2
"System 3" --> UC3
"System 4" --> UC4
@enduml
