@startuml
actor A1
actor A2
actor A3
usecase UC1
usecase UC2
usecase UC3
usecase UC4
usecase UC5
A1 --> UC1
A1 --> UC2
A2 --> UC2
A2 --> UC3
A3 --> UC3
A3 --> UC4
A1 --> UC5
A2 --> UC5
A3 --> UC5
UC1 .> UC5 : <<include>>
UC4 .> UC5 : <<include>>
@enduml
