@startuml
actor Actor1
actor Actor2
actor Actor3
actor Actor4
actor Actor5
Actor5 --> (Use Case)
usecase "Use Case"
Actor2 --|> Actor1
Actor3 --|> Actor2
Actor4 --|> Actor3
Actor5 --|> Actor4
@enduml
