@startuml
top to bottom direction
actor User
rectangle System {
  usecase UC1 <<primary>>
  usecase UC2 <<primary>>
  usecase UC3 <<primary>>
  usecase UC4 <<primary>>
}
User --> UC1
User --> UC2
User --> UC3
User --> UC4
@enduml
