@startuml
actor Entity
actor LegalEntity
actor Person
actor Organization
actor Company
actor NonProfit
LegalEntity --|> Entity
Person --|> LegalEntity
Organization --|> LegalEntity
Company --|> Organization
NonProfit --|> Organization
usecase "File Taxes" as FT
usecase "Register" as REG
Person --> FT
Company --> FT
NonProfit --> REG
@enduml
