@startuml
actor User
usecase Base1
usecase Base2
usecase Sub1
usecase Sub2
usecase Sub3
usecase Sub4
Sub1 .> Base2 : <<include>>
Sub2 .> Base1 : <<include>>
Sub3 .> Base2 : <<include>>
Sub4 .> Base1 : <<include>>
User --> Base1
User --> Base2
@enduml
