@startuml
actor User
usecase UC1
usecase UC2
usecase UC3
usecase UC4
usecase UC5
UC1 .> UC2 : <<include>>
UC2 .> UC3 : <<include>>
UC3 .> UC4 : <<include>>
UC4 .> UC5 : <<include>>
User --> UC1
@enduml
