@startuml
left to right direction
actor A1
actor A2
actor A3
package "Pkg1" {
  usecase "UC1A"
  usecase "UC1B"
}
package "Pkg2" {
  usecase "UC2A"
  usecase "UC2B"
}
A1 --> (UC1A)
A2 --> (UC1A)
A3 --> (UC1A)
A1 --> (UC2A)
A2 --> (UC2A)
A3 --> (UC2A)
@enduml
