@startuml
actor Parent
actor Child1
actor Child2
actor Child3
actor Child4
usecase BaseUC
usecase SpecialUC
usecase CommonUC
Child1 --|> Parent
Child2 --|> Parent
Child3 --|> Parent
Child4 --|> Parent
Parent --> BaseUC
Child1 --> SpecialUC
Child2 --> SpecialUC
Child3 --> SpecialUC
Child4 --> SpecialUC
BaseUC .> CommonUC : <<include>>
SpecialUC .> CommonUC : <<include>>
@enduml
