@startuml
actor BaseActor
actor DerivedActor
DerivedActor --|> BaseActor
usecase Base
usecase Derived
usecase Included
usecase Extended
usecase Optional
Derived --|> Base
Base .> Included : <<include>>
Extended .> Base : <<extend>>
Optional .> Base : <<extend>>
BaseActor --> Base
DerivedActor --> Derived
@enduml
