@startuml
actor Person
actor Employee
actor Manager
Employee --|> Person
Manager --|> Employee
usecase "Work" as W
usecase "Manage Team" as MT
usecase "Approve Budget" as AB
Employee --> W
Manager --> MT
Manager --> AB
@enduml
