@startuml
actor Actor1
actor Actor2
actor Actor3
usecase SharedUC1
usecase SharedUC2
Actor1 --> SharedUC1
Actor1 --> SharedUC2
Actor2 --> SharedUC1
Actor2 --> SharedUC2
Actor3 --> SharedUC1
Actor3 --> SharedUC2
@enduml
