@startuml
skinparam usecase {
  BackgroundColor LightBlue
  BorderColor DarkBlue
  ArrowColor Navy
}
skinparam actor {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}
actor User
usecase "Action"
User --> (Action)
@enduml
