@startuml
actor Actor
package "Package1" {
  usecase "Action1A"
  usecase "Action1B"
}
package "Package2" {
  usecase "Action2A"
  usecase "Action2B"
}
package "Package3" {
  usecase "Action3A"
  usecase "Action3B"
}
Actor --> (Action1A)
Actor --> (Action1B)
Actor --> (Action2A)
Actor --> (Action2B)
Actor --> (Action3A)
Actor --> (Action3B)
@enduml
