@startuml
top to bottom direction
actor A1
actor A2
package "Pkg1" {
  usecase "UC1A"
  usecase "UC1B"
}
package "Pkg2" {
  usecase "UC2A"
  usecase "UC2B"
}
package "Pkg3" {
  usecase "UC3A"
  usecase "UC3B"
}
A1 --> (UC1A)
A2 --> (UC1A)
A1 --> (UC2A)
A2 --> (UC2A)
A1 --> (UC3A)
A2 --> (UC3A)
@enduml
