@startuml
frame Review2FrameCtl6801 {
  class Review2FrameLeafCtl6803
  folder Review2EmptyCtl6805 {
  }
  node Review2NodeCtl6807 {
    class Review2NodeLeafCtl6809
  }
  class Review2FrameTailCtl6811
}

class Review2RootCtl6813
Review2FrameLeafCtl6803 --> Review2RootCtl6813
@enduml
