@startuml
participant "Right Descent Worker" as Worker
activate Worker
activate Worker
activate Worker
Worker -->] : recurring border message
Worker -->] -- : recurring border message
Worker -->] : recurring border message
Worker -->] -- : recurring border message
Worker -->] : recurring border message
Worker -->] -- : recurring border message
Worker -->] : recurring border message
@enduml
