@startuml
class Resource10 [[https://example.com/resource/10{Resource 10 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource10
  [[https://example.com/resource/10 Click here]] for more info
end note
@enduml
