@startuml
class Resource48 [[https://example.com/resource/48{Resource 48 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource48
  [[https://example.com/resource/48 Click here]] for more info
end note
@enduml
