@startuml
class Resource36 [[https://example.com/resource/36{Resource 36 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource36
  [[https://example.com/resource/36 Click here]] for more info
end note
@enduml
