@startuml
class Resource12 [[https://example.com/resource/12{Resource 12 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource12
  [[https://example.com/resource/12 Click here]] for more info
end note
@enduml
