@startuml
class Resource38 [[https://example.com/resource/38{Resource 38 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource38
  [[https://example.com/resource/38 Click here]] for more info
end note
@enduml
