@startuml
class Resource50 [[https://example.com/resource/50{Resource 50 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource50
  [[https://example.com/resource/50 Click here]] for more info
end note
@enduml
