@startuml
class Resource22 [[https://example.com/resource/22{Resource 22 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource22
  [[https://example.com/resource/22 Click here]] for more info
end note
@enduml
