@startuml
class Resource24 [[https://example.com/resource/24{Resource 24 documentation}]] {
  * id : int
  + getName() : String
  + setName(n : String) : void
}
note right of Resource24
  [[https://example.com/resource/24 Click here]] for more info
end note
@enduml
