@startuml
top to bottom direction
node RenderSource431
database RenderSink433
RenderSource431 --> RenderSink433 : **replicate**\n//phase two//
note bottom on link
  first **bold** row 431
  second //italic// row O0Il
end note
@enduml
