@startsalt
{^Security Settings
  Firewall: | "               "
  VPN: | "               "
  Proxy: | "               "
  Certificate: | "               "
  ..
  [Save] | [Reset] | [Cancel]
}
@endsalt
