@startsalt
{
  Field0: | "               "
  Field1: | "               "
  Field2: | "               "
  Field3: | "               "
  Field4: | "               "
  Field5: | "               "
  ..
  [Btn0] | [Btn1]
}
@endsalt
