@startsalt
{^Network Settings
  Hostname: | "               "
  DNS Server: | "               "
  Gateway: | "               "
  Subnet Mask: | "               "
  ..
  [Save] | [Reset] | [Cancel]
}
@endsalt
