@startsalt
{
  Label0: | "            "
  Label1: | "            "
  Label2: | "            "
  ..
  [X] Check option 0
  [ ] Check option 1
  ..
  (X) Radio 0
  ( ) Radio 1
  ( ) Radio 2
  ..
  [Submit]
}
@endsalt
