@startsalt
{^Create New Project
  Project Name:    | "                    "
  Description:     | {SI
    Enter description
    here
  }
  ..
  Template:        | ^Blank^
  (X) Private project
  ( ) Public project
  ..
  Collaborators:
  {T
    + Team Members
    ++ Alice (owner)
    ++ Bob
    ++ Charlie
  }
  ..
  [  Create  ] | [ Cancel ]
}
@endsalt
