@startsalt
{^Video Settings
  Resolution: | "               "
  Brightness: | "               "
  Contrast: | "               "
  Saturation: | "               "
  ..
  [Save] | [Reset] | [Cancel]
}
@endsalt
