@startboard
Reading List

+Want to Read+
* The Pragmatic Programmer
* Clean Architecture

+Reading+
* Designing Data-Intensive Applications

+On Hold+
* Domain-Driven Design

+Finished+
* The Rust Programming Language
* Programming Rust
@endboard
