@startboard
Mega Project

+Icebox+
* Idea A
* Idea B
* Idea C
* Idea D

+Backlog+
* Task 1
* Task 2
* Task 3

+In Progress+
* Task 4
* Task 5

+Review+
* Task 6

+Done+
* Task 7
* Task 8
* Task 9
* Task 10
@endboard
