@startboard
Q4 Campaign

+Concept+
* Holiday promo
* Year-end review

+Creative+
* Banner designs

+Approval+
* Budget sign-off

+Scheduled+
* Email blast Dec 1

+Live+
* Black Friday campaign
@endboard
