@startboard
Scrum Board

+Product Backlog+
* Epic: Search
* Epic: Analytics

+Sprint Backlog+
* US-10 Basic search
* US-11 Filters

+In Sprint+
* US-09 Results page

+Done+
* US-08 Index page
@endboard
