@startboard
SDLC Workflow

+Requirements+
* FR-001 Login
* FR-002 Search

+Design+
* FR-001 Login UI mockup

+Development+
* FR-001 Backend API

+Integration+
* FR-001 End-to-end

+UAT+
* FR-001 User testing

+Production+
* v1.0.0 release
@endboard
