@startuml
left to right direction
package "Implicit First 8471" as ImplicitFirst8473 {
  [ImplicitShared8475] --> [ImplicitPeer8477]
}
package "Implicit Second 8479" as ImplicitSecond8481 {
  component "Implicit Final 8483" as ImplicitShared8475 <<resolved>> [[https://final.example/implicit]] #Wheat
  component ImplicitSecondProbe8485
}
@enduml
