@startebnf
version = major , "." , minor , "." , patch , [ "-" , pre_release ] , [ "+" , build ];
major = numeric_id;
minor = numeric_id;
patch = numeric_id;
pre_release = pre_id , { "." , pre_id };
build = build_id , { "." , build_id };
pre_id = numeric_id | ident;
build_id = numeric_id | ident;
numeric_id = "0" | ( non_zero , { digit } );
ident = { letter | digit | "-" };
non_zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
digit = "0" | non_zero;
letter = "a" | "b" | "c";
@endebnf
