@startebnf
program = { statement };
statement = if_stmt | while_stmt | assign_stmt;
if_stmt = "if" , condition , "then" , statement , [ "else" , statement ];
while_stmt = "while" , condition , "do" , statement;
assign_stmt = identifier , ":=" , expression;
condition = expression , rel_op , expression;
rel_op = "=" | "<" | ">" | "<=" | ">=";
expression = identifier | number;
identifier = letter;
number = digit;
letter = "a" | "b" | "c";
digit = "0" | "1" | "2";
@endebnf
