@startebnf
phone = [ country_code ] , area_code , "-" , exchange , "-" , subscriber;
country_code = "+" , digit , { digit };
area_code = "(" , digit , digit , digit , ")";
exchange = digit , digit , digit;
subscriber = digit , digit , digit , digit;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
@endebnf
