@startebnf
element = start_tag , content , end_tag | empty_element;
start_tag = "<" , name , { attribute } , ">";
end_tag = "</" , name , ">";
empty_element = "<" , name , { attribute } , "/>";
content = { element | char_data };
attribute = name , "=" , quoted_string;
quoted_string = '"' , { char } , '"';
name = letter , { letter | digit | "-" | "_" };
char_data = { char };
char = letter | digit;
letter = "a" | "b" | "c";
digit = "0" | "1" | "2";
@endebnf
