@startuml
participant Participant
actor Actor
boundary Boundary
control Control
entity Entity
database Database
collections Collections
queue Queue
Participant -> Actor: 1
Actor -> Boundary: 2
Boundary -> Control: 3
Control -> Entity: 4
Entity -> Database: 5
Database -> Collections: 6
Collections -> Queue: 7
@enduml
