@startuml
class C0
class C1
class C2
class C3
class C4
class C5
class C6
class C7
class C8
class C9
class C10
class C11
class C12
class C13
class C14
class C15
class C16
class C17
class C18
class C19
class C20
class C21
class C22
class C23
class C24
C0 --> C1
C1 --> C2
C2 --> C3
C3 --> C4
C4 --> C5
C5 --> C6
C6 --> C7
C7 --> C8
C8 --> C9
C9 --> C10
C10 --> C11
C11 --> C12
C12 --> C13
C13 --> C14
C14 --> C15
C15 --> C16
C16 --> C17
C17 --> C18
C18 --> C19
C19 --> C20
C20 --> C21
C21 --> C22
C22 --> C23
C23 --> C24
C24 --> C0
@enduml
