@startuml
class Note0
class Note1
class Note2
class Note3
class Note4
class Note5
class Note6
class Note7
class Note8
class Note9
note right of Note0: This is note number 0
note right of Note1: This is note number 1
note right of Note2: This is note number 2
note right of Note3: This is note number 3
note right of Note4: This is note number 4
note right of Note5: This is note number 5
note right of Note6: This is note number 6
note right of Note7: This is note number 7
note right of Note8: This is note number 8
note right of Note9: This is note number 9
@enduml
