@startuml
title This is an extremely long title that This is an extremely long title that This is an extremely long title that This is an extremely long title that This is an extremely long title that 
class Foo
@enduml
