@startuml
!define MACRO0 value0
!define MACRO1 value1
!define MACRO2 value2
!define MACRO3 value3
!define MACRO4 value4
!define MACRO5 value5
!define MACRO6 value6
!define MACRO7 value7
!define MACRO8 value8
!define MACRO9 value9
!define MACRO10 value10
!define MACRO11 value11
!define MACRO12 value12
!define MACRO13 value13
!define MACRO14 value14
!define MACRO15 value15
!define MACRO16 value16
!define MACRO17 value17
!define MACRO18 value18
!define MACRO19 value19
class Foo
@enduml
