@startuml
class Foo {
  field1: String
  field2: int
  field3: float
  field4: boolean
  field5: Date
  method1(): void
  method2(): String
  method3(a: int, b: int): int
  method4(x: String): boolean
  method5(): List<String>
}
@enduml
