@startuml
nwdiag {
  network internet {
    address = "192.168.0.0/24"
    WebServer [address = "192.168.0.1"]
  }
  network internal {
    WebServer
    DBServer [address = "10.0.0.1"]
  }
}
@enduml
