@startuml
skinparam sequence {
  ActorBorderColor DarkBlue
  ActorBackgroundColor LightBlue
  ParticipantBorderColor DarkGreen
  ParticipantBackgroundColor LightGreen
  ArrowColor DarkRed
  LifeLineBorderColor Gray
}
actor User
participant System
User -> System: request
@enduml
