@startuml
Alice -> Bob: This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on and on This is a very long label that goes on a
@enduml
