@startuml
concise "Signal 0" as S0
concise "Signal 1" as S1
@0
S0 is Low
S1 is High
@20
S0 is High
S1 is Unknown
@40
S0 is Unknown
S1 is HighZ
@60
S0 is HighZ
S1 is Low
@80
S0 is Low
S1 is High
@100
S0 is High
S1 is Unknown
@120
S0 is Unknown
S1 is HighZ
@140
S0 is HighZ
S1 is Low
@160
S0 is Low
S1 is High
@180
S0 is High
S1 is Unknown
@enduml
