@startuml
skinparam stereotype {
  CBackgroundColor<< Service >> LightBlue
  CBorderColor<< Service >> Blue
  CBackgroundColor<< Repository >> LightGreen
  CBorderColor<< Repository >> Green
}
class Foo << Service >>
class Bar << Repository >>
Foo --> Bar
@enduml
