@startuml
class Level0
class Level1
class Level2
class Level3
class Level4
class Level5
class Level6
class Level7
class Level8
class Level9
class Level10
class Level11
class Level12
class Level13
class Level14
Level0 <|-- Level1
Level1 <|-- Level2
Level2 <|-- Level3
Level3 <|-- Level4
Level4 <|-- Level5
Level5 <|-- Level6
Level6 <|-- Level7
Level7 <|-- Level8
Level8 <|-- Level9
Level9 <|-- Level10
Level10 <|-- Level11
Level11 <|-- Level12
Level12 <|-- Level13
Level13 <|-- Level14
@enduml
