@startuml
concise "Signal 0" as S0
concise "Signal 1" as S1
concise "Signal 2" as S2
concise "Signal 3" as S3
concise "Signal 4" as S4
@0
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@20
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@40
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@60
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@80
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@100
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@120
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@140
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@160
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@180
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@200
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@220
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@240
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@260
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@280
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@300
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@320
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@340
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@360
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@380
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@400
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@420
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
S4 is High
@440
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
S4 is Unknown
@460
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
S4 is HighZ
@480
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
S4 is Low
@enduml
