@startuml
class C0
class C1
class C2
class C3
class C4
class C5
class C6
class C7
class C8
class C9
C0 --> C1
C1 --> C2
C2 --> C3
C3 --> C4
C4 --> C5
C5 --> C6
C6 --> C7
C7 --> C8
C8 --> C9
C9 --> C0
@enduml
