@startuml
skinparam class {
  BackgroundColor LightBlue
  BorderColor DarkBlue
  FontColor Black
  FontSize 12
  FontName Arial
  HeaderBackgroundColor Blue
  StereotypeFontColor Gray
}
class Foo {
  field: String
}
class Bar
Foo --> Bar
@enduml
