@startuml
concise "Signal 0" as S0
concise "Signal 1" as S1
concise "Signal 2" as S2
concise "Signal 3" as S3
@0
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
@20
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
@40
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
@60
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
@80
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
@100
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
@120
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
@140
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
@160
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
@180
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
@200
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
@220
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
@240
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
@260
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
@280
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
@300
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
@320
S0 is Low
S1 is High
S2 is Unknown
S3 is HighZ
@340
S0 is High
S1 is Unknown
S2 is HighZ
S3 is Low
@360
S0 is Unknown
S1 is HighZ
S2 is Low
S3 is High
@380
S0 is HighZ
S1 is Low
S2 is High
S3 is Unknown
@enduml
