@startuml
|Lane0|
start
|Lane0|
:Step 1;
|Lane1|
:Step 2;
|Lane2|
:Step 3;
|Lane3|
:Step 4;
|Lane4|
:Step 5;
|Lane0|
:Step 6;
|Lane1|
:Step 7;
|Lane2|
:Step 8;
|Lane3|
:Step 9;
|Lane4|
:Step 10;
stop
@enduml
