@startuml
skinparam classBackgroundColor LightBlue
skinparam classBorderColor DarkBlue
skinparam classHeaderBackgroundColor Blue
skinparam classFontColor White
skinparam arrowColor DarkRed
class Foo
class Bar
Foo --> Bar
@enduml
