@startuml
start
if (a?) then (yes)
  if (b?) then (yes)
    :both true;
  else (no)
    :only a;
  endif
else (no)
  if (b?) then (yes)
    :only b;
  else (no)
    :neither;
  endif
endif
stop
@enduml
