@startuml
class S1 <<stereotype1>>
class S2 <<stereotype2>>
class S3 <<service>>
class S4 <<repository>>
class S5 <<entity>>
class S6 <<controller>>
class S7 <<boundary>>
class S8 <<dto>>
class S9 <<pojo>>
class S10 <<interface>>
@enduml
