@startuml
class Foo
note right of Foo
This is paragraph line 0 of a very large note with lots of content.
This is paragraph line 1 of a very large note with lots of content.
This is paragraph line 2 of a very large note with lots of content.
This is paragraph line 3 of a very large note with lots of content.
This is paragraph line 4 of a very large note with lots of content.
This is paragraph line 5 of a very large note with lots of content.
This is paragraph line 6 of a very large note with lots of content.
This is paragraph line 7 of a very large note with lots of content.
This is paragraph line 8 of a very large note with lots of content.
This is paragraph line 9 of a very large note with lots of content.
This is paragraph line 10 of a very large note with lots of content.
This is paragraph line 11 of a very large note with lots of content.
This is paragraph line 12 of a very large note with lots of content.
This is paragraph line 13 of a very large note with lots of content.
This is paragraph line 14 of a very large note with lots of content.
This is paragraph line 15 of a very large note with lots of content.
This is paragraph line 16 of a very large note with lots of content.
This is paragraph line 17 of a very large note with lots of content.
This is paragraph line 18 of a very large note with lots of content.
This is paragraph line 19 of a very large note with lots of content.
This is paragraph line 20 of a very large note with lots of content.
This is paragraph line 21 of a very large note with lots of content.
This is paragraph line 22 of a very large note with lots of content.
This is paragraph line 23 of a very large note with lots of content.
This is paragraph line 24 of a very large note with lots of content.
This is paragraph line 25 of a very large note with lots of content.
This is paragraph line 26 of a very large note with lots of content.
This is paragraph line 27 of a very large note with lots of content.
This is paragraph line 28 of a very large note with lots of content.
This is paragraph line 29 of a very large note with lots of content.
end note
@enduml
