@startuml
left to right direction
participant W0
participant W1
participant W2
participant W3
participant W4
participant W5
participant W6
participant W7
participant W8
participant W9
participant W10
participant W11
participant W12
participant W13
participant W14
participant W15
participant W16
participant W17
participant W18
participant W19
W0 -> W19: long range
@enduml
