@startuml
title "Component Diagram 222"
package "System222" {
  [Service1_222]
  [Service2_222]
  [Service3_222]
  [Service4_222]
  [Service5_222]
}
[Service1_222] --> [Service2_222]
[Service2_222] --> [Service3_222]
[Service3_222] --> [Service4_222]
[Service4_222] --> [Service5_222]
@enduml
