@startuml
title "Class Diagram 265"
class Entity1_265 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_265 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_265 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_265 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_265 --|> Entity2_265
Entity2_265 --|> Entity3_265
Entity3_265 --|> Entity4_265
@enduml
