@startuml
title "Class Diagram 291"
class Entity1_291 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_291 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_291 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_291 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_291 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_291 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_291 --|> Entity2_291
Entity2_291 --|> Entity3_291
Entity3_291 --|> Entity4_291
Entity4_291 --|> Entity5_291
Entity5_291 --|> Entity6_291
@enduml
