@startuml
title "State Machine 151"
state State1_151
state State2_151
state State3_151
state State4_151
[*] --> State1_151
State1_151 --> State2_151 : event_1
State2_151 --> State3_151 : event_2
State3_151 --> State4_151 : event_3
State4_151 --> [*] : done
@enduml
