@startuml
title "State Machine 194"
state State1_194
state State2_194
state State3_194
state State4_194
state State5_194
state State6_194
state State7_194
[*] --> State1_194
State1_194 --> State2_194 : event_1
State2_194 --> State3_194 : event_2
State3_194 --> State4_194 : event_3
State4_194 --> State5_194 : event_4
State5_194 --> State6_194 : event_5
State6_194 --> State7_194 : event_6
State7_194 --> [*] : done
@enduml
