@startuml
title "Component Diagram 205"
package "System205" {
  [Service1_205]
  [Service2_205]
  [Service3_205]
  [Service4_205]
}
[Service1_205] --> [Service2_205]
[Service2_205] --> [Service3_205]
[Service3_205] --> [Service4_205]
@enduml
