@startuml
title "State Machine 173"
state State1_173
state State2_173
state State3_173
state State4_173
state State5_173
state State6_173
[*] --> State1_173
State1_173 --> State2_173 : event_1
State2_173 --> State3_173 : event_2
State3_173 --> State4_173 : event_3
State4_173 --> State5_173 : event_4
State5_173 --> State6_173 : event_5
State6_173 --> [*] : done
@enduml
