@startuml
title "Class Diagram 267"
class Entity1_267 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_267 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_267 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_267 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_267 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_267 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_267 --|> Entity2_267
Entity2_267 --|> Entity3_267
Entity3_267 --|> Entity4_267
Entity4_267 --|> Entity5_267
Entity5_267 --|> Entity6_267
@enduml
