@startuml
title "Class Diagram 276"
class Entity1_276 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_276 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_276 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_276 --|> Entity2_276
Entity2_276 --|> Entity3_276
@enduml
