@startuml
title "Class Diagram 296"
class Entity1_296 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_296 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_296 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_296 --|> Entity2_296
Entity2_296 --|> Entity3_296
@enduml
