@startuml
title "Class Diagram 268"
class Entity1_268 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_268 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_268 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_268 --|> Entity2_268
Entity2_268 --|> Entity3_268
@enduml
