@startuml
title "Combo Variant 33"
[Component1_33]
[Component2_33]
[Component3_33]
[Component4_33]
[Component5_33]
[Component6_33]
[Component1_33] --> [Component2_33]
[Component2_33] --> [Component3_33]
[Component3_33] --> [Component4_33]
[Component4_33] --> [Component5_33]
[Component5_33] --> [Component6_33]
@enduml
