@startuml
title "Component Diagram 235"
package "System235" {
  [Service1_235]
  [Service2_235]
  [Service3_235]
  [Service4_235]
  [Service5_235]
  [Service6_235]
}
[Service1_235] --> [Service2_235]
[Service2_235] --> [Service3_235]
[Service3_235] --> [Service4_235]
[Service4_235] --> [Service5_235]
[Service5_235] --> [Service6_235]
@enduml
