@startuml
title "Class Diagram 253"
class Entity1_253 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_253 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_253 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_253 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_253 --|> Entity2_253
Entity2_253 --|> Entity3_253
Entity3_253 --|> Entity4_253
@enduml
