@startuml
title "Class Diagram 280"
class Entity1_280 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_280 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_280 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_280 --|> Entity2_280
Entity2_280 --|> Entity3_280
@enduml
