@startuml
title "State Machine 177"
state State1_177
state State2_177
state State3_177
state State4_177
state State5_177
[*] --> State1_177
State1_177 --> State2_177 : event_1
State2_177 --> State3_177 : event_2
State3_177 --> State4_177 : event_3
State4_177 --> State5_177 : event_4
State5_177 --> [*] : done
@enduml
