@startuml
title "Component Diagram 230"
package "System230" {
  [Service1_230]
  [Service2_230]
  [Service3_230]
  [Service4_230]
  [Service5_230]
}
[Service1_230] --> [Service2_230]
[Service2_230] --> [Service3_230]
[Service3_230] --> [Service4_230]
[Service4_230] --> [Service5_230]
@enduml
