@startuml
title "Class Diagram 294"
class Entity1_294 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_294 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_294 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_294 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_294 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_294 --|> Entity2_294
Entity2_294 --|> Entity3_294
Entity3_294 --|> Entity4_294
Entity4_294 --|> Entity5_294
@enduml
