@startuml
title "Class Diagram 279"
class Entity1_279 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_279 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_279 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_279 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_279 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_279 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_279 --|> Entity2_279
Entity2_279 --|> Entity3_279
Entity3_279 --|> Entity4_279
Entity4_279 --|> Entity5_279
Entity5_279 --|> Entity6_279
@enduml
