@startuml
title "State Machine 168"
state State1_168
state State2_168
state State3_168
state State4_168
state State5_168
state State6_168
[*] --> State1_168
State1_168 --> State2_168 : event_1
State2_168 --> State3_168 : event_2
State3_168 --> State4_168 : event_3
State4_168 --> State5_168 : event_4
State5_168 --> State6_168 : event_5
State6_168 --> [*] : done
@enduml
