@startuml
class N1 { +f() }
class N2 { +f() }
class N3 { +f() }
class N4 { +f() }
class N5 { +f() }
class N6 { +f() }
class N7 { +f() }
class N8 { +f() }

N1 --> N2
N2 --> N3
N3 --> N4
N4 --> N5
N5 --> N6
N6 --> N7
N7 --> N8
N1 --> N5
N2 --> N7
N3 --> N8
N4 --> N1
N6 --> N2
N8 --> N3
@enduml
