@startuml
title "State Machine 154"
state State1_154
state State2_154
state State3_154
state State4_154
state State5_154
state State6_154
state State7_154
[*] --> State1_154
State1_154 --> State2_154 : event_1
State2_154 --> State3_154 : event_2
State3_154 --> State4_154 : event_3
State4_154 --> State5_154 : event_4
State5_154 --> State6_154 : event_5
State6_154 --> State7_154 : event_6
State7_154 --> [*] : done
@enduml
