@startuml
title "State Machine 191"
state State1_191
state State2_191
state State3_191
state State4_191
[*] --> State1_191
State1_191 --> State2_191 : event_1
State2_191 --> State3_191 : event_2
State3_191 --> State4_191 : event_3
State4_191 --> [*] : done
@enduml
