@startuml
title "Component Diagram 233"
package "System233" {
  [Service1_233]
  [Service2_233]
  [Service3_233]
  [Service4_233]
}
[Service1_233] --> [Service2_233]
[Service2_233] --> [Service3_233]
[Service3_233] --> [Service4_233]
@enduml
