@startuml
title "Component Diagram 203"
package "System203" {
  [Service1_203]
  [Service2_203]
  [Service3_203]
  [Service4_203]
  [Service5_203]
  [Service6_203]
}
[Service1_203] --> [Service2_203]
[Service2_203] --> [Service3_203]
[Service3_203] --> [Service4_203]
[Service4_203] --> [Service5_203]
[Service5_203] --> [Service6_203]
@enduml
