@startuml
title "Component Diagram 225"
package "System225" {
  [Service1_225]
  [Service2_225]
  [Service3_225]
  [Service4_225]
}
[Service1_225] --> [Service2_225]
[Service2_225] --> [Service3_225]
[Service3_225] --> [Service4_225]
@enduml
