@startuml
title "Class Diagram 273"
class Entity1_273 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_273 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_273 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_273 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_273 --|> Entity2_273
Entity2_273 --|> Entity3_273
Entity3_273 --|> Entity4_273
@enduml
