@startuml
title "State Machine 184"
state State1_184
state State2_184
state State3_184
state State4_184
state State5_184
state State6_184
state State7_184
[*] --> State1_184
State1_184 --> State2_184 : event_1
State2_184 --> State3_184 : event_2
State3_184 --> State4_184 : event_3
State4_184 --> State5_184 : event_4
State5_184 --> State6_184 : event_5
State6_184 --> State7_184 : event_6
State7_184 --> [*] : done
@enduml
