@startuml
title "State Machine 160"
state State1_160
state State2_160
state State3_160
[*] --> State1_160
State1_160 --> State2_160 : event_1
State2_160 --> State3_160 : event_2
State3_160 --> [*] : done
@enduml
