@startuml
title "Class Diagram 300"
class Entity1_300 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_300 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_300 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_300 --|> Entity2_300
Entity2_300 --|> Entity3_300
@enduml
