@startuml
title "Package Diagram 320"
package "PKG1" {
  class pkg1Model { +id : int }
  class pkg1Service { +process() }
}
package "PKG2" {
  class pkg2Model { +id : int }
  class pkg2Service { +process() }
}
package "PKG3" {
  class pkg3Model { +id : int }
  class pkg3Service { +process() }
}
package "PKG4" {
  class pkg4Model { +id : int }
  class pkg4Service { +process() }
}

pkg1Service --> pkg2Model
pkg2Service --> pkg3Model
pkg3Service --> pkg4Model
@enduml
