@startuml
title "State Machine 199"
state State1_199
state State2_199
state State3_199
state State4_199
state State5_199
state State6_199
state State7_199
[*] --> State1_199
State1_199 --> State2_199 : event_1
State2_199 --> State3_199 : event_2
State3_199 --> State4_199 : event_3
State4_199 --> State5_199 : event_4
State5_199 --> State6_199 : event_5
State6_199 --> State7_199 : event_6
State7_199 --> [*] : done
@enduml
