@startuml
class L1 { + f() }
class L2 { + f() }
class L3 { + f() }
class L4 { + f() }
class L5 { + f() }
class L6 { + f() }
class L7 { + f() }
class L8 { + f() }
class L9 { + f() }
class L10 { + f() }
class L11 { + f() }
class L12 { + f() }
class L13 { + f() }
class L14 { + f() }
class L15 { + f() }

L1 --> L2
L2 --> L3
L3 --> L4
L4 --> L5
L5 --> L6
L6 --> L7
L7 --> L8
L8 --> L9
L9 --> L10
L10 --> L11
L11 --> L12
L12 --> L13
L13 --> L14
L14 --> L15
@enduml
