@startuml
title "Sequence 127"
participant Svc1
participant Svc2
participant Svc3
participant Svc4
participant Svc5
participant Svc6
Svc1 -> Svc2 : call_1_127
Svc2 -> Svc3 : call_2_127
Svc3 -> Svc4 : call_3_127
Svc4 -> Svc5 : call_4_127
Svc5 -> Svc6 : call_5_127
@enduml
