@startuml
title "Class Diagram 287"
class Entity1_287 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_287 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_287 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_287 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_287 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_287 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_287 --|> Entity2_287
Entity2_287 --|> Entity3_287
Entity3_287 --|> Entity4_287
Entity4_287 --|> Entity5_287
Entity5_287 --|> Entity6_287
@enduml
