@startuml
title "Class Diagram 288"
class Entity1_288 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_288 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_288 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_288 --|> Entity2_288
Entity2_288 --|> Entity3_288
@enduml
