@startuml
title "State Machine 162"
state State1_162
state State2_162
state State3_162
state State4_162
state State5_162
[*] --> State1_162
State1_162 --> State2_162 : event_1
State2_162 --> State3_162 : event_2
State3_162 --> State4_162 : event_3
State4_162 --> State5_162 : event_4
State5_162 --> [*] : done
@enduml
