@startuml
title "State Machine 190"
state State1_190
state State2_190
state State3_190
[*] --> State1_190
State1_190 --> State2_190 : event_1
State2_190 --> State3_190 : event_2
State3_190 --> [*] : done
@enduml
