@startuml
title "Component Diagram 215"
package "System215" {
  [Service1_215]
  [Service2_215]
  [Service3_215]
  [Service4_215]
  [Service5_215]
  [Service6_215]
}
[Service1_215] --> [Service2_215]
[Service2_215] --> [Service3_215]
[Service3_215] --> [Service4_215]
[Service4_215] --> [Service5_215]
[Service5_215] --> [Service6_215]
@enduml
