@startuml
title "Class Diagram 270"
class Entity1_270 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_270 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_270 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_270 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_270 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_270 --|> Entity2_270
Entity2_270 --|> Entity3_270
Entity3_270 --|> Entity4_270
Entity4_270 --|> Entity5_270
@enduml
