@startuml
title "Component Diagram 234"
package "System234" {
  [Service1_234]
  [Service2_234]
  [Service3_234]
  [Service4_234]
  [Service5_234]
}
[Service1_234] --> [Service2_234]
[Service2_234] --> [Service3_234]
[Service3_234] --> [Service4_234]
[Service4_234] --> [Service5_234]
@enduml
