@startuml
title "Class Diagram 295"
class Entity1_295 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_295 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_295 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_295 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_295 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_295 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_295 --|> Entity2_295
Entity2_295 --|> Entity3_295
Entity3_295 --|> Entity4_295
Entity4_295 --|> Entity5_295
Entity5_295 --|> Entity6_295
@enduml
