@startuml
title "Class Diagram 290"
class Entity1_290 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_290 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_290 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_290 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_290 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_290 --|> Entity2_290
Entity2_290 --|> Entity3_290
Entity3_290 --|> Entity4_290
Entity4_290 --|> Entity5_290
@enduml
