@startuml
title "State Machine 197"
state State1_197
state State2_197
state State3_197
state State4_197
state State5_197
[*] --> State1_197
State1_197 --> State2_197 : event_1
State2_197 --> State3_197 : event_2
State3_197 --> State4_197 : event_3
State4_197 --> State5_197 : event_4
State5_197 --> [*] : done
@enduml
