@startuml
title "State Machine 156"
state State1_156
state State2_156
state State3_156
state State4_156
[*] --> State1_156
State1_156 --> State2_156 : event_1
State2_156 --> State3_156 : event_2
State3_156 --> State4_156 : event_3
State4_156 --> [*] : done
@enduml
