@startuml
title "Class Diagram 271"
class Entity1_271 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_271 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_271 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_271 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_271 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_271 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_271 --|> Entity2_271
Entity2_271 --|> Entity3_271
Entity3_271 --|> Entity4_271
Entity4_271 --|> Entity5_271
Entity5_271 --|> Entity6_271
@enduml
