@startuml
title "Class Diagram 266"
class Entity1_266 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_266 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_266 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_266 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_266 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_266 --|> Entity2_266
Entity2_266 --|> Entity3_266
Entity3_266 --|> Entity4_266
Entity4_266 --|> Entity5_266
@enduml
