@startuml
title "State Machine 175"
state State1_175
state State2_175
state State3_175
[*] --> State1_175
State1_175 --> State2_175 : event_1
State2_175 --> State3_175 : event_2
State3_175 --> [*] : done
@enduml
