@startuml
title "Class Diagram 298"
class Entity1_298 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_298 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_298 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_298 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_298 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_298 --|> Entity2_298
Entity2_298 --|> Entity3_298
Entity3_298 --|> Entity4_298
Entity4_298 --|> Entity5_298
@enduml
