@startuml
title "Class Diagram 299"
class Entity1_299 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_299 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_299 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_299 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_299 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
class Entity6_299 {
  - id : Long
  + getId() : Long
  + process_6() : void
}
Entity1_299 --|> Entity2_299
Entity2_299 --|> Entity3_299
Entity3_299 --|> Entity4_299
Entity4_299 --|> Entity5_299
Entity5_299 --|> Entity6_299
@enduml
