@startuml
title "Class Diagram 269"
class Entity1_269 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_269 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_269 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_269 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_269 --|> Entity2_269
Entity2_269 --|> Entity3_269
Entity3_269 --|> Entity4_269
@enduml
