@startuml
title "State Machine 178"
state State1_178
state State2_178
state State3_178
state State4_178
state State5_178
state State6_178
[*] --> State1_178
State1_178 --> State2_178 : event_1
State2_178 --> State3_178 : event_2
State3_178 --> State4_178 : event_3
State4_178 --> State5_178 : event_4
State5_178 --> State6_178 : event_5
State6_178 --> [*] : done
@enduml
