@startuml
title "Creole Formatting Showcase"

class RichFormattingDemo {
  + __underline__Field : String
  + --strikethrough--Field : int
  + **boldField** : boolean
  + //italicField// : double
  + ""monospaceField"" : byte[]
}

note top of RichFormattingDemo
  = Heading 1
  == Heading 2
  === Heading 3
  ----
  * Bullet one
  * Bullet two
  ** Sub-bullet
  *** Deep sub-bullet
  # Numbered one
  # Numbered two
  ## Sub-numbered
  ----
  | Col 1 | Col 2 | Col 3 |
  | a     | b     | c     |
  | x     | y     | z     |
  ----
  <b>Bold</b> <i>Italic</i> <u>Underline</u>
  <color:red>Red</color> <color:#00FF00>Green</color>
  <back:yellow>Yellow background</back>
  <size:20>Large</size> <size:8>Small</size>
  <s>Strikethrough</s> <w>Wave</w>
  ~~strikethrough2~~
end note
@enduml
