@startuml
title "State Machine 187"
state State1_187
state State2_187
state State3_187
state State4_187
state State5_187
[*] --> State1_187
State1_187 --> State2_187 : event_1
State2_187 --> State3_187 : event_2
State3_187 --> State4_187 : event_3
State4_187 --> State5_187 : event_4
State5_187 --> [*] : done
@enduml
