@startuml
title "State Machine 196"
state State1_196
state State2_196
state State3_196
state State4_196
[*] --> State1_196
State1_196 --> State2_196 : event_1
State2_196 --> State3_196 : event_2
State3_196 --> State4_196 : event_3
State4_196 --> [*] : done
@enduml
