@startuml
title "Class Diagram 289"
class Entity1_289 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_289 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_289 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_289 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_289 --|> Entity2_289
Entity2_289 --|> Entity3_289
Entity3_289 --|> Entity4_289
@enduml
