@startuml
title "Component Diagram 226"
package "System226" {
  [Service1_226]
  [Service2_226]
  [Service3_226]
  [Service4_226]
  [Service5_226]
}
[Service1_226] --> [Service2_226]
[Service2_226] --> [Service3_226]
[Service3_226] --> [Service4_226]
[Service4_226] --> [Service5_226]
@enduml
