@startuml
title "Class Diagram 297"
class Entity1_297 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_297 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_297 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_297 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_297 --|> Entity2_297
Entity2_297 --|> Entity3_297
Entity3_297 --|> Entity4_297
@enduml
