@startuml
title "Class Diagram 272"
class Entity1_272 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_272 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_272 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
Entity1_272 --|> Entity2_272
Entity2_272 --|> Entity3_272
@enduml
