@startuml
title "Component Diagram 206"
package "System206" {
  [Service1_206]
  [Service2_206]
  [Service3_206]
  [Service4_206]
  [Service5_206]
}
[Service1_206] --> [Service2_206]
[Service2_206] --> [Service3_206]
[Service3_206] --> [Service4_206]
[Service4_206] --> [Service5_206]
@enduml
