@startuml
title "State Machine 167"
state State1_167
state State2_167
state State3_167
state State4_167
state State5_167
[*] --> State1_167
State1_167 --> State2_167 : event_1
State2_167 --> State3_167 : event_2
State3_167 --> State4_167 : event_3
State4_167 --> State5_167 : event_4
State5_167 --> [*] : done
@enduml
