@startuml
title "State Machine 180"
state State1_180
state State2_180
state State3_180
[*] --> State1_180
State1_180 --> State2_180 : event_1
State2_180 --> State3_180 : event_2
State3_180 --> [*] : done
@enduml
