@startuml
title "Class Diagram 261"
class Entity1_261 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_261 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_261 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_261 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
Entity1_261 --|> Entity2_261
Entity2_261 --|> Entity3_261
Entity3_261 --|> Entity4_261
@enduml
