@startuml
title "Class Diagram 286"
class Entity1_286 {
  - id : Long
  + getId() : Long
  + process_1() : void
}
class Entity2_286 {
  - id : Long
  + getId() : Long
  + process_2() : void
}
class Entity3_286 {
  - id : Long
  + getId() : Long
  + process_3() : void
}
class Entity4_286 {
  - id : Long
  + getId() : Long
  + process_4() : void
}
class Entity5_286 {
  - id : Long
  + getId() : Long
  + process_5() : void
}
Entity1_286 --|> Entity2_286
Entity2_286 --|> Entity3_286
Entity3_286 --|> Entity4_286
Entity4_286 --|> Entity5_286
@enduml
