@startuml
!include <archimate/Archimate>

Business_Process(e0, "Element 0")
Application_Component(e1, "Element 1")
Application_Service(e2, "Element 2")
Technology_Node(e3, "Element 3")

Rel_Serving(e0, e1, "")
Rel_Composition(e1, e2, "")
Rel_Aggregation(e2, e3, "")
@enduml
