@startuml
!include <archimate/Archimate>

Application_Component(e0, "Element 0")
Application_Service(e1, "Element 1")
Technology_Node(e2, "Element 2")
Technology_SystemSoftware(e3, "Element 3")

Rel_Aggregation(e0, e1, "")
Rel_Triggering(e1, e2, "")
Rel_Realization(e2, e3, "")
@enduml
