@startuml
!include <archimate/Archimate>

Business_Actor(e0, "Element 0")
Business_Role(e1, "Element 1")
Business_Process(e2, "Element 2")
Application_Component(e3, "Element 3")

Rel_Aggregation(e0, e1, "")
Rel_Triggering(e1, e2, "")
Rel_Realization(e2, e3, "")
@enduml
