@startuml
!include <archimate/Archimate>

Application_Component(e0, "Element 0")
Application_Service(e1, "Element 1")
Technology_Node(e2, "Element 2")
Technology_SystemSoftware(e3, "Element 3")
Business_Actor(e4, "Element 4")
Business_Role(e5, "Element 5")

Rel_Serving(e0, e1, "")
Rel_Composition(e1, e2, "")
Rel_Aggregation(e2, e3, "")
Rel_Triggering(e3, e4, "")
Rel_Realization(e4, e5, "")
@enduml
