@startuml
!include <archimate/Archimate>

Technology_Node(e0, "Element 0")
Technology_SystemSoftware(e1, "Element 1")
Business_Actor(e2, "Element 2")

Rel_Association(e0, e1, "")
Rel_Serving(e1, e2, "")
@enduml
