@startuml
!include <archimate/Archimate>

Motivation_Stakeholder(stakeholder, "Customer")
Motivation_Goal(goal, "Reduce Costs")
Motivation_Requirement(req, "24h Availability")

Rel_Association_Up(stakeholder, goal, "has")
Rel_Realization_Up(req, goal, "realizes")
@enduml
