@startuml
!include <archimate/Archimate>

Business_Process(e0, "Element 0")
Application_Component(e1, "Element 1")
Application_Service(e2, "Element 2")
Technology_Node(e3, "Element 3")
Technology_SystemSoftware(e4, "Element 4")
Business_Actor(e5, "Element 5")

Rel_Realization(e0, e1, "")
Rel_Association(e1, e2, "")
Rel_Serving(e2, e3, "")
Rel_Composition(e3, e4, "")
Rel_Aggregation(e4, e5, "")
@enduml
