@startuml
!include <archimate/Archimate>

Application_Service(e0, "Element 0")
Technology_Node(e1, "Element 1")
Technology_SystemSoftware(e2, "Element 2")

Rel_Composition(e0, e1, "")
Rel_Aggregation(e1, e2, "")
@enduml
