@startuml
!include <archimate/Archimate>

Technology_SystemSoftware(e0, "Element 0")
Business_Actor(e1, "Element 1")
Business_Role(e2, "Element 2")

Rel_Composition(e0, e1, "")
Rel_Aggregation(e1, e2, "")
@enduml
