@startuml
!include <archimate/Archimate>

Application_Component(e0, "Element 0")
Application_Service(e1, "Element 1")
Technology_Node(e2, "Element 2")

Rel_Association(e0, e1, "")
Rel_Serving(e1, e2, "")
@enduml
