@startuml
!include <archimate/Archimate>

Business_Actor(e0, "Element 0")
Business_Role(e1, "Element 1")
Business_Process(e2, "Element 2")

Rel_Triggering(e0, e1, "")
Rel_Realization(e1, e2, "")
@enduml
