@startuml
object Source #yellow {
  id = 3
  type = "source"
}
object Target #cyan {
  id = 103
  type = "target"
}
Source o-- Target : "has"
note right of Source : Source note
note left of Target : Target note
@enduml
