@startuml
map "Map0_5" as m0_5 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_5" as m1_5 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_5" as m2_5 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}

m0_5 --> m1_5
m1_5 --> m2_5
@enduml
