@startuml
object Obj0_11 { val = 110 }
object Obj1_11 { val = 111 }
object Obj2_11 { val = 112 }
object Obj3_11 { val = 113 }
object Obj4_11 { val = 114 }
object Obj5_11 { val = 115 }
object Obj6_11 { val = 116 }
Obj0_11 --> Obj1_11
Obj1_11 --> Obj2_11
Obj2_11 --> Obj3_11
Obj3_11 --> Obj4_11
Obj4_11 --> Obj5_11
Obj5_11 --> Obj6_11
Obj6_11 --> Obj0_11
@enduml
