@startuml
object Obj0_23 { val = 230 }
object Obj1_23 { val = 231 }
object Obj2_23 { val = 232 }
object Obj3_23 { val = 233 }
object Obj4_23 { val = 234 }
object Obj5_23 { val = 235 }
object Obj6_23 { val = 236 }
Obj0_23 --> Obj1_23
Obj1_23 --> Obj2_23
Obj2_23 --> Obj3_23
Obj3_23 --> Obj4_23
Obj4_23 --> Obj5_23
Obj5_23 --> Obj6_23
Obj6_23 --> Obj0_23
@enduml
