@startuml
object Obj0_21 { val = 210 }
object Obj1_21 { val = 211 }
object Obj2_21 { val = 212 }
object Obj3_21 { val = 213 }
object Obj4_21 { val = 214 }
Obj0_21 --> Obj1_21
Obj1_21 --> Obj2_21
Obj2_21 --> Obj3_21
Obj3_21 --> Obj4_21
Obj4_21 --> Obj0_21
@enduml
