@startuml
object Source #blue {
  id = 1
  type = "source"
}
object Target #orange {
  id = 101
  type = "target"
}
Source ..> Target : "uses"
note right of Source : Source note
note left of Target : Target note
@enduml
