@startuml
object Obj0_20 { val = 200 }
object Obj1_20 { val = 201 }
object Obj2_20 { val = 202 }
object Obj3_20 { val = 203 }
Obj0_20 --> Obj1_20
Obj1_20 --> Obj2_20
Obj2_20 --> Obj3_20
Obj3_20 --> Obj0_20
@enduml
