@startuml
object Obj10A <<entity>> #red {
  id = 10
  name = "obj10a"
  active = true
}
object Obj10B #blue {
  ref = 10
  label = "obj10b"
}
Obj10A --> Obj10B : "ref_10"
note right of Obj10A : Object variant 10
@enduml
