@startuml
object Obj0_35 { val = 350 }
object Obj1_35 { val = 351 }
object Obj2_35 { val = 352 }
object Obj3_35 { val = 353 }
object Obj4_35 { val = 354 }
object Obj5_35 { val = 355 }
object Obj6_35 { val = 356 }
Obj0_35 --> Obj1_35
Obj1_35 --> Obj2_35
Obj2_35 --> Obj3_35
Obj3_35 --> Obj4_35
Obj4_35 --> Obj5_35
Obj5_35 --> Obj6_35
Obj6_35 --> Obj0_35
@enduml
