@startuml
object Obj0_4 { val = 40 }
object Obj1_4 { val = 41 }
object Obj2_4 { val = 42 }
object Obj3_4 { val = 43 }
object Obj4_4 { val = 44 }
object Obj5_4 { val = 45 }
Obj0_4 --> Obj1_4
Obj1_4 --> Obj2_4
Obj2_4 --> Obj3_4
Obj3_4 --> Obj4_4
Obj4_4 --> Obj5_4
Obj5_4 --> Obj0_4
@enduml
