@startuml
map "Map0_26" as m0_26 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_26" as m1_26 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_26" as m2_26 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}
map "Map3_26" as m3_26 {
  field0 => val3_0
  field1 => val3_1
  field2 => val3_2
}

m0_26 --> m1_26
m1_26 --> m2_26
m2_26 --> m3_26
@enduml
