@startuml
map "Source2" as src2 {
  entry0 => data2_0
  entry1 => data2_1
  entry2 => data2_2
  entry3 => data2_3
  entry4 => data2_4
}
map "Target2" as tgt2 {
  x0 => y2_0
  x1 => y2_1
}
src2::entry0 --> tgt2
@enduml
