@startuml
object Obj0_29 { val = 290 }
object Obj1_29 { val = 291 }
object Obj2_29 { val = 292 }
object Obj3_29 { val = 293 }
object Obj4_29 { val = 294 }
object Obj5_29 { val = 295 }
object Obj6_29 { val = 296 }
Obj0_29 --> Obj1_29
Obj1_29 --> Obj2_29
Obj2_29 --> Obj3_29
Obj3_29 --> Obj4_29
Obj4_29 --> Obj5_29
Obj5_29 --> Obj6_29
Obj6_29 --> Obj0_29
@enduml
