@startuml
map "Source3" as src3 {
  entry0 => data3_0
  entry1 => data3_1
  entry2 => data3_2
  entry3 => data3_3
  entry4 => data3_4
  entry5 => data3_5
}
map "Target3" as tgt3 {
  x0 => y3_0
  x1 => y3_1
}
src3::entry0 --> tgt3
@enduml
