@startuml
map "Map0_11" as m0_11 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_11" as m1_11 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_11" as m2_11 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}
map "Map3_11" as m3_11 {
  field0 => val3_0
  field1 => val3_1
  field2 => val3_2
}
map "Map4_11" as m4_11 {
  field0 => val4_0
  field1 => val4_1
  field2 => val4_2
}

m0_11 --> m1_11
m1_11 --> m2_11
m2_11 --> m3_11
m3_11 --> m4_11
@enduml
