@startuml
object Obj0_22 { val = 220 }
object Obj1_22 { val = 221 }
object Obj2_22 { val = 222 }
object Obj3_22 { val = 223 }
object Obj4_22 { val = 224 }
object Obj5_22 { val = 225 }
Obj0_22 --> Obj1_22
Obj1_22 --> Obj2_22
Obj2_22 --> Obj3_22
Obj3_22 --> Obj4_22
Obj4_22 --> Obj5_22
Obj5_22 --> Obj0_22
@enduml
