@startuml
map "Map0_2" as m0_2 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_2" as m1_2 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_2" as m2_2 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}
map "Map3_2" as m3_2 {
  field0 => val3_0
  field1 => val3_1
  field2 => val3_2
}

m0_2 --> m1_2
m1_2 --> m2_2
m2_2 --> m3_2
@enduml
