@startuml
object Obj0_39 { val = 390 }
object Obj1_39 { val = 391 }
object Obj2_39 { val = 392 }
object Obj3_39 { val = 393 }
object Obj4_39 { val = 394 }
Obj0_39 --> Obj1_39
Obj1_39 --> Obj2_39
Obj2_39 --> Obj3_39
Obj3_39 --> Obj4_39
Obj4_39 --> Obj0_39
@enduml
