@startuml
object Node0 { v = 0 }
object Node1 { v = 1 }
object Node2 { v = 2 }
object Node3 { v = 3 }
object Node4 { v = 4 }
object Node5 { v = 5 }
object Node6 { v = 6 }
object Node7 { v = 7 }
Node0 --> Node1
Node1 --> Node2
Node2 --> Node3
Node3 --> Node4
Node4 --> Node5
Node5 --> Node6
Node6 --> Node7
@enduml
