@startuml
object Obj0_32 { val = 320 }
object Obj1_32 { val = 321 }
object Obj2_32 { val = 322 }
object Obj3_32 { val = 323 }
Obj0_32 --> Obj1_32
Obj1_32 --> Obj2_32
Obj2_32 --> Obj3_32
Obj3_32 --> Obj0_32
@enduml
