@startuml
object Obj0_34 { val = 340 }
object Obj1_34 { val = 341 }
object Obj2_34 { val = 342 }
object Obj3_34 { val = 343 }
object Obj4_34 { val = 344 }
object Obj5_34 { val = 345 }
Obj0_34 --> Obj1_34
Obj1_34 --> Obj2_34
Obj2_34 --> Obj3_34
Obj3_34 --> Obj4_34
Obj4_34 --> Obj5_34
Obj5_34 --> Obj0_34
@enduml
