@startuml
object Root {
  id = 1
}
object Child1 {
  parent_id = 1
}
object Child2 {
  parent_id = 1
}
object GrandChild {
  parent_id = 2
}
Root --> Child1
Root --> Child2
Child1 --> GrandChild
@enduml
