@startuml
object O0_0 { v = 0 }
object O0_1 { v = 1 }
object O0_2 { v = 2 }
object O0_3 { v = 3 }
object O1_0 { v = 10 }
object O1_1 { v = 11 }
object O1_2 { v = 12 }
object O1_3 { v = 13 }
object O2_0 { v = 20 }
object O2_1 { v = 21 }
object O2_2 { v = 22 }
object O2_3 { v = 23 }
O0_0 --> O0_1
O0_1 --> O0_2
O0_2 --> O0_3
O1_0 --> O1_1
O1_1 --> O1_2
O1_2 --> O1_3
O2_0 --> O2_1
O2_1 --> O2_2
O2_2 --> O2_3
O0_0 --> O1_0
O0_1 --> O1_1
O0_2 --> O1_2
O0_3 --> O1_3
O1_0 --> O2_0
O1_1 --> O2_1
O1_2 --> O2_2
O1_3 --> O2_3
@enduml
