@startuml
object Obj0_14 { val = 140 }
object Obj1_14 { val = 141 }
object Obj2_14 { val = 142 }
object Obj3_14 { val = 143 }
Obj0_14 --> Obj1_14
Obj1_14 --> Obj2_14
Obj2_14 --> Obj3_14
Obj3_14 --> Obj0_14
@enduml
