@startuml
map "Map0_22" as m0_22 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_22" as m1_22 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_22" as m2_22 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}
map "Map3_22" as m3_22 {
  field0 => val3_0
  field1 => val3_1
  field2 => val3_2
}

m0_22 --> m1_22
m1_22 --> m2_22
m2_22 --> m3_22
@enduml
