@startuml
map "Source6" as src6 {
  entry0 => data6_0
  entry1 => data6_1
  entry2 => data6_2
  entry3 => data6_3
  entry4 => data6_4
}
map "Target6" as tgt6 {
  x0 => y6_0
  x1 => y6_1
}
src6::entry0 --> tgt6
@enduml
