@startuml
object Obj0_28 { val = 280 }
object Obj1_28 { val = 281 }
object Obj2_28 { val = 282 }
object Obj3_28 { val = 283 }
object Obj4_28 { val = 284 }
object Obj5_28 { val = 285 }
Obj0_28 --> Obj1_28
Obj1_28 --> Obj2_28
Obj2_28 --> Obj3_28
Obj3_28 --> Obj4_28
Obj4_28 --> Obj5_28
Obj5_28 --> Obj0_28
@enduml
