@startuml
object Source #red {
  id = 0
  type = "source"
}
object Target #yellow {
  id = 100
  type = "target"
}
Source --|> Target : "extends"
note right of Source : Source note
note left of Target : Target note
@enduml
