@startuml
map "Map0_21" as m0_21 {
  field0 => val0_0
  field1 => val0_1
  field2 => val0_2
}
map "Map1_21" as m1_21 {
  field0 => val1_0
  field1 => val1_1
  field2 => val1_2
}
map "Map2_21" as m2_21 {
  field0 => val2_0
  field1 => val2_1
  field2 => val2_2
}

m0_21 --> m1_21
m1_21 --> m2_21
@enduml
