@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.11.0/24"
    srv00 [address = "10.0.0.11"]
    srv01 [address = "10.0.1.11"]
    srv02 [address = "10.0.2.11"]
    srv03 [address = "10.0.3.11"]
    srv04 [address = "10.0.4.11"]
  }
  network net1 {
    address = "10.1.11.0/24"
    srv01 [address = "10.1.0.11"]
    srv02 [address = "10.1.1.11"]
    srv03 [address = "10.1.2.11"]
    srv04 [address = "10.1.3.11"]
  }
  network net2 {
    address = "10.2.11.0/24"
    srv02 [address = "10.2.0.11"]
    srv03 [address = "10.2.1.11"]
    srv04 [address = "10.2.2.11"]
  }
  network net3 {
    address = "10.3.11.0/24"
    srv03 [address = "10.3.0.11"]
    srv04 [address = "10.3.1.11"]
  }
}
@endnwdiag
