@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.6.0/24"
    srv00 [address = "10.0.0.6"]
    srv01 [address = "10.0.1.6"]
    srv02 [address = "10.0.2.6"]
    srv03 [address = "10.0.3.6"]
  }
  network net1 {
    address = "10.1.6.0/24"
    srv01 [address = "10.1.0.6"]
    srv02 [address = "10.1.1.6"]
    srv03 [address = "10.1.2.6"]
  }
}
@endnwdiag
