@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.18.0/24"
    srv00 [address = "10.0.0.18"]
    srv01 [address = "10.0.1.18"]
    srv02 [address = "10.0.2.18"]
    srv03 [address = "10.0.3.18"]
  }
  network net1 {
    address = "10.1.18.0/24"
    srv01 [address = "10.1.0.18"]
    srv02 [address = "10.1.1.18"]
    srv03 [address = "10.1.2.18"]
  }
}
@endnwdiag
