@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.7.0/24"
    srv00 [address = "10.0.0.7"]
    srv01 [address = "10.0.1.7"]
    srv02 [address = "10.0.2.7"]
    srv03 [address = "10.0.3.7"]
    srv04 [address = "10.0.4.7"]
  }
  network net1 {
    address = "10.1.7.0/24"
    srv01 [address = "10.1.0.7"]
    srv02 [address = "10.1.1.7"]
    srv03 [address = "10.1.2.7"]
    srv04 [address = "10.1.3.7"]
  }
  network net2 {
    address = "10.2.7.0/24"
    srv02 [address = "10.2.0.7"]
    srv03 [address = "10.2.1.7"]
    srv04 [address = "10.2.2.7"]
  }
}
@endnwdiag
