@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.5.0/24"
    srv00 [address = "10.0.0.5"]
    srv01 [address = "10.0.1.5"]
    srv02 [address = "10.0.2.5"]
  }
  network net1 {
    address = "10.1.5.0/24"
    srv01 [address = "10.1.0.5"]
    srv02 [address = "10.1.1.5"]
  }
  network net2 {
    address = "10.2.5.0/24"
    srv02 [address = "10.2.0.5"]
    srv00 [address = "10.2.1.5"]
  }
  network net3 {
    address = "10.3.5.0/24"
    srv00 [address = "10.3.0.5"]
    srv01 [address = "10.3.1.5"]
  }
}
@endnwdiag
