@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.3.0/24"
    srv00 [address = "10.0.0.3"]
    srv01 [address = "10.0.1.3"]
    srv02 [address = "10.0.2.3"]
    srv03 [address = "10.0.3.3"]
    srv04 [address = "10.0.4.3"]
  }
  network net1 {
    address = "10.1.3.0/24"
    srv01 [address = "10.1.0.3"]
    srv02 [address = "10.1.1.3"]
    srv03 [address = "10.1.2.3"]
    srv04 [address = "10.1.3.3"]
  }
}
@endnwdiag
