@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.13.0/24"
    srv00 [address = "10.0.0.13"]
    srv01 [address = "10.0.1.13"]
    srv02 [address = "10.0.2.13"]
  }
  network net1 {
    address = "10.1.13.0/24"
    srv01 [address = "10.1.0.13"]
    srv02 [address = "10.1.1.13"]
  }
  network net2 {
    address = "10.2.13.0/24"
    srv02 [address = "10.2.0.13"]
    srv00 [address = "10.2.1.13"]
  }
}
@endnwdiag
