@startnwdiag
nwdiag {
  network net0 {
    address = "10.0.10.0/24"
    srv00 [address = "10.0.0.10"]
    srv01 [address = "10.0.1.10"]
    srv02 [address = "10.0.2.10"]
    srv03 [address = "10.0.3.10"]
  }
  network net1 {
    address = "10.1.10.0/24"
    srv01 [address = "10.1.0.10"]
    srv02 [address = "10.1.1.10"]
    srv03 [address = "10.1.2.10"]
  }
  network net2 {
    address = "10.2.10.0/24"
    srv02 [address = "10.2.0.10"]
    srv03 [address = "10.2.1.10"]
  }
}
@endnwdiag
