@startnwdiag
nwdiag {
  network internet {
    address = "0.0.0.0/0"
    firewall [address = "1.2.3.4"]
  }
  network dmz {
    address = "192.168.1.0/24"
    firewall [address = "192.168.1.1"]
    web01    [address = "192.168.1.10"]
    web02    [address = "192.168.1.11"]
    mail01   [address = "192.168.1.20"]
  }
  network internal {
    address = "10.0.0.0/24"
    firewall [address = "10.0.0.1"]
    web01    [address = "10.0.0.10"]
    app01    [address = "10.0.0.20"]
    db01     [address = "10.0.0.30"]
  }
}
@endnwdiag
