@startnwdiag
nwdiag {
  network net0_4 {
    address = "172.16.4.0/24"
    node0_0_4 [address = "172.16.4.1"]
    node0_1_4 [address = "172.16.4.2"]
    node0_2_4 [address = "172.16.4.3"]
  }
  network net1_4 {
    address = "172.17.4.0/24"
    node0_2_4 [address = "172.17.4.1"]
    node1_0_4 [address = "172.17.4.2"]
    node1_1_4 [address = "172.17.4.3"]
  }
}
@endnwdiag
