@startnwdiag
nwdiag {
  network net0_21 {
    address = "172.16.21.0/24"
    node0_0_21 [address = "172.16.21.1"]
    node0_1_21 [address = "172.16.21.2"]
  }
  network net1_21 {
    address = "172.17.21.0/24"
    node0_1_21 [address = "172.17.21.1"]
    node1_0_21 [address = "172.17.21.2"]
  }
  network net2_21 {
    address = "172.18.21.0/24"
    node1_1_21 [address = "172.18.21.1"]
    node2_0_21 [address = "172.18.21.2"]
  }
}
@endnwdiag
