@startnwdiag
nwdiag {
  network net0_8 {
    address = "172.16.8.0/24"
    node0_0_8 [address = "172.16.8.1"]
    node0_1_8 [address = "172.16.8.2"]
    node0_2_8 [address = "172.16.8.3"]
    node0_3_8 [address = "172.16.8.4"]
  }
  network net1_8 {
    address = "172.17.8.0/24"
    node0_3_8 [address = "172.17.8.1"]
    node1_0_8 [address = "172.17.8.2"]
    node1_1_8 [address = "172.17.8.3"]
    node1_2_8 [address = "172.17.8.4"]
  }
}
@endnwdiag
