@startnwdiag
nwdiag {
  network net0_7 {
    address = "172.16.7.0/24"
    node0_0_7 [address = "172.16.7.1"]
    node0_1_7 [address = "172.16.7.2"]
    node0_2_7 [address = "172.16.7.3"]
  }
  network net1_7 {
    address = "172.17.7.0/24"
    node0_2_7 [address = "172.17.7.1"]
    node1_0_7 [address = "172.17.7.2"]
    node1_1_7 [address = "172.17.7.3"]
  }
  network net2_7 {
    address = "172.18.7.0/24"
    node1_2_7 [address = "172.18.7.1"]
    node2_0_7 [address = "172.18.7.2"]
    node2_1_7 [address = "172.18.7.3"]
  }
  network net3_7 {
    address = "172.19.7.0/24"
    node2_2_7 [address = "172.19.7.1"]
    node3_0_7 [address = "172.19.7.2"]
    node3_1_7 [address = "172.19.7.3"]
  }
  network net4_7 {
    address = "172.20.7.0/24"
    node3_2_7 [address = "172.20.7.1"]
    node4_0_7 [address = "172.20.7.2"]
    node4_1_7 [address = "172.20.7.3"]
  }
}
@endnwdiag
