@startnwdiag
nwdiag {
  network net0_2 {
    address = "172.16.2.0/24"
    node0_0_2 [address = "172.16.2.1"]
    node0_1_2 [address = "172.16.2.2"]
    node0_2_2 [address = "172.16.2.3"]
    node0_3_2 [address = "172.16.2.4"]
  }
  network net1_2 {
    address = "172.17.2.0/24"
    node0_3_2 [address = "172.17.2.1"]
    node1_0_2 [address = "172.17.2.2"]
    node1_1_2 [address = "172.17.2.3"]
    node1_2_2 [address = "172.17.2.4"]
  }
  network net2_2 {
    address = "172.18.2.0/24"
    node1_3_2 [address = "172.18.2.1"]
    node2_0_2 [address = "172.18.2.2"]
    node2_1_2 [address = "172.18.2.3"]
    node2_2_2 [address = "172.18.2.4"]
  }
  network net3_2 {
    address = "172.19.2.0/24"
    node2_3_2 [address = "172.19.2.1"]
    node3_0_2 [address = "172.19.2.2"]
    node3_1_2 [address = "172.19.2.3"]
    node3_2_2 [address = "172.19.2.4"]
  }
}
@endnwdiag
