@startnwdiag
nwdiag {
  network net0_5 {
    address = "172.16.5.0/24"
    node0_0_5 [address = "172.16.5.1"]
    node0_1_5 [address = "172.16.5.2"]
    node0_2_5 [address = "172.16.5.3"]
    node0_3_5 [address = "172.16.5.4"]
  }
  network net1_5 {
    address = "172.17.5.0/24"
    node0_3_5 [address = "172.17.5.1"]
    node1_0_5 [address = "172.17.5.2"]
    node1_1_5 [address = "172.17.5.3"]
    node1_2_5 [address = "172.17.5.4"]
  }
  network net2_5 {
    address = "172.18.5.0/24"
    node1_3_5 [address = "172.18.5.1"]
    node2_0_5 [address = "172.18.5.2"]
    node2_1_5 [address = "172.18.5.3"]
    node2_2_5 [address = "172.18.5.4"]
  }
}
@endnwdiag
