@startnwdiag
nwdiag {
  network net0_9 {
    address = "172.16.9.0/24"
    node0_0_9 [address = "172.16.9.1"]
    node0_1_9 [address = "172.16.9.2"]
  }
  network net1_9 {
    address = "172.17.9.0/24"
    node0_1_9 [address = "172.17.9.1"]
    node1_0_9 [address = "172.17.9.2"]
  }
  network net2_9 {
    address = "172.18.9.0/24"
    node1_1_9 [address = "172.18.9.1"]
    node2_0_9 [address = "172.18.9.2"]
  }
}
@endnwdiag
