@startnwdiag
nwdiag {
  group grp0_3 {
    color = "#FFE4E1"
    srv0_0_3 srv0_1_3
  }
  group grp1_3 {
    color = "#E1F5FE"
    srv1_0_3 srv1_1_3
  }
  network net_3 {
    address = "10.3.0.0/24"
    srv0_0_3
    srv0_1_3
    srv1_0_3
    srv1_1_3
  }
}
@endnwdiag
