@startnwdiag
nwdiag {
  group grp0_8 {
    color = "#FFE4E1"
    srv0_0_8 srv0_1_8
  }
  group grp1_8 {
    color = "#E1F5FE"
    srv1_0_8 srv1_1_8
  }
  group grp2_8 {
    color = "#E8F5E9"
    srv2_0_8 srv2_1_8
  }
  group grp3_8 {
    color = "#FFF9C4"
    srv3_0_8 srv3_1_8
  }
  network net_8 {
    address = "10.8.0.0/24"
    srv0_0_8
    srv0_1_8
    srv1_0_8
    srv1_1_8
    srv2_0_8
    srv2_1_8
    srv3_0_8
    srv3_1_8
  }
}
@endnwdiag
