@startnwdiag
nwdiag {
  group grp0_9 {
    color = "#FFE4E1"
    srv0_0_9 srv0_1_9
  }
  group grp1_9 {
    color = "#E1F5FE"
    srv1_0_9 srv1_1_9
  }
  network net_9 {
    address = "10.9.0.0/24"
    srv0_0_9
    srv0_1_9
    srv1_0_9
    srv1_1_9
  }
}
@endnwdiag
