@startnwdiag
nwdiag {
  group control_plane {
    color = "#F0E6FF"
    apiserver
    scheduler
    etcd
  }
  group worker_nodes {
    color = "#E6F0FF"
    node1
    node2
    node3
  }
  network cluster_network {
    address = "10.96.0.0/12"
    apiserver  [address = "10.96.0.1"]
    scheduler  [address = "10.96.0.2"]
    etcd       [address = "10.96.0.3"]
    node1      [address = "10.96.1.1"]
    node2      [address = "10.96.1.2"]
    node3      [address = "10.96.1.3"]
  }
  network pod_network {
    address = "192.168.0.0/16"
    node1  [address = "192.168.1.0"]
    node2  [address = "192.168.2.0"]
    node3  [address = "192.168.3.0"]
  }
}
@endnwdiag
