@startnwdiag
nwdiag {
  network peering {
    as1_router [address = "192.0.2.1"]
    as2_router [address = "192.0.2.2"]
  }
  network as1 {
    address = "10.1.0.0/16"
    as1_router [address = "10.1.0.1"]
    as1_web    [address = "10.1.0.10"]
  }
  network as2 {
    address = "10.2.0.0/16"
    as2_router [address = "10.2.0.1"]
    as2_web    [address = "10.2.0.10"]
  }
}
@endnwdiag
