@startnwdiag
nwdiag {
  network mpls {
    address = "10.0.0.0/8"
    hq_router    [address = "10.0.0.1"]
    site_a_router [address = "10.0.1.1"]
    site_b_router [address = "10.0.2.1"]
  }
  network internet {
    address = "0.0.0.0/0"
    hq_router    [address = "1.1.1.1"]
    site_a_router [address = "2.2.2.2"]
    site_b_router [address = "3.3.3.3"]
  }
  network hq_lan {
    address = "192.168.0.0/24"
    hq_router [address = "192.168.0.1"]
    hq_pc1    [address = "192.168.0.10"]
    hq_pc2    [address = "192.168.0.11"]
    hq_server [address = "192.168.0.100"]
  }
  network site_a {
    address = "192.168.1.0/24"
    site_a_router [address = "192.168.1.1"]
    site_a_pc1    [address = "192.168.1.10"]
  }
  network site_b {
    address = "192.168.2.0/24"
    site_b_router [address = "192.168.2.1"]
    site_b_pc1    [address = "192.168.2.10"]
  }
}
@endnwdiag
