@startnwdiag
nwdiag {
  network internet {
    address = "203.0.113.0/24"
    web01 [address = "203.0.113.10"]
    web02 [address = "203.0.113.11"]
  }
  network internal {
    address = "10.0.0.0/24"
    web01 [address = "10.0.0.10"]
    web02 [address = "10.0.0.11"]
    db01  [address = "10.0.0.20"]
  }
}
@endnwdiag
