@startnwdiag
nwdiag {
  network vlan0_14 {
    address = "10.1.4.0/24"
    host0_0_14 [address = "10.1.4.1"]
    host0_1_14 [address = "10.1.4.2"]
    host0_2_14 [address = "10.1.4.3"]
    host0_3_14 [address = "10.1.4.4"]
  }
  network vlan1_14 {
    address = "10.2.4.0/24"
    router0_14 [address = "10.2.4.1"]
    host1_1_14 [address = "10.2.4.2"]
    host1_2_14 [address = "10.2.4.3"]
    host1_3_14 [address = "10.2.4.4"]
  }
  network vlan2_14 {
    address = "10.3.4.0/24"
    router1_14 [address = "10.3.4.1"]
    host2_1_14 [address = "10.3.4.2"]
    host2_2_14 [address = "10.3.4.3"]
    host2_3_14 [address = "10.3.4.4"]
  }
  network vlan3_14 {
    address = "10.4.4.0/24"
    router2_14 [address = "10.4.4.1"]
    host3_1_14 [address = "10.4.4.2"]
    host3_2_14 [address = "10.4.4.3"]
    host3_3_14 [address = "10.4.4.4"]
  }
}
@endnwdiag
