@startnwdiag
nwdiag {
  network vlan0_8 {
    address = "10.1.8.0/24"
    host0_0_8 [address = "10.1.8.1"]
    host0_1_8 [address = "10.1.8.2"]
  }
  network vlan1_8 {
    address = "10.2.8.0/24"
    router0_8 [address = "10.2.8.1"]
    host1_1_8 [address = "10.2.8.2"]
  }
  network vlan2_8 {
    address = "10.3.8.0/24"
    router1_8 [address = "10.3.8.1"]
    host2_1_8 [address = "10.3.8.2"]
  }
  network vlan3_8 {
    address = "10.4.8.0/24"
    router2_8 [address = "10.4.8.1"]
    host3_1_8 [address = "10.4.8.2"]
  }
}
@endnwdiag
