@startnwdiag
nwdiag {
  network vlan0_7 {
    address = "10.1.7.0/24"
    host0_0_7 [address = "10.1.7.1"]
    host0_1_7 [address = "10.1.7.2"]
    host0_2_7 [address = "10.1.7.3"]
    host0_3_7 [address = "10.1.7.4"]
    host0_4_7 [address = "10.1.7.5"]
  }
  network vlan1_7 {
    address = "10.2.7.0/24"
    router0_7 [address = "10.2.7.1"]
    host1_1_7 [address = "10.2.7.2"]
    host1_2_7 [address = "10.2.7.3"]
    host1_3_7 [address = "10.2.7.4"]
    host1_4_7 [address = "10.2.7.5"]
  }
  network vlan2_7 {
    address = "10.3.7.0/24"
    router1_7 [address = "10.3.7.1"]
    host2_1_7 [address = "10.3.7.2"]
    host2_2_7 [address = "10.3.7.3"]
    host2_3_7 [address = "10.3.7.4"]
    host2_4_7 [address = "10.3.7.5"]
  }
}
@endnwdiag
