@startnwdiag
nwdiag {
  network vlan0_2 {
    address = "10.1.2.0/24"
    host0_0_2 [address = "10.1.2.1"]
    host0_1_2 [address = "10.1.2.2"]
    host0_2_2 [address = "10.1.2.3"]
    host0_3_2 [address = "10.1.2.4"]
  }
  network vlan1_2 {
    address = "10.2.2.0/24"
    router0_2 [address = "10.2.2.1"]
    host1_1_2 [address = "10.2.2.2"]
    host1_2_2 [address = "10.2.2.3"]
    host1_3_2 [address = "10.2.2.4"]
  }
  network vlan2_2 {
    address = "10.3.2.0/24"
    router1_2 [address = "10.3.2.1"]
    host2_1_2 [address = "10.3.2.2"]
    host2_2_2 [address = "10.3.2.3"]
    host2_3_2 [address = "10.3.2.4"]
  }
  network vlan3_2 {
    address = "10.4.2.0/24"
    router2_2 [address = "10.4.2.1"]
    host3_1_2 [address = "10.4.2.2"]
    host3_2_2 [address = "10.4.2.3"]
    host3_3_2 [address = "10.4.2.4"]
  }
}
@endnwdiag
