@startnwdiag
nwdiag {
  network vlan0_4 {
    address = "10.1.4.0/24"
    host0_0_4 [address = "10.1.4.1"]
    host0_1_4 [address = "10.1.4.2"]
  }
  network vlan1_4 {
    address = "10.2.4.0/24"
    router0_4 [address = "10.2.4.1"]
    host1_1_4 [address = "10.2.4.2"]
  }
  network vlan2_4 {
    address = "10.3.4.0/24"
    router1_4 [address = "10.3.4.1"]
    host2_1_4 [address = "10.3.4.2"]
  }
}
@endnwdiag
