@startnwdiag
nwdiag {
  network vlan0_9 {
    address = "10.1.9.0/24"
    host0_0_9 [address = "10.1.9.1"]
    host0_1_9 [address = "10.1.9.2"]
    host0_2_9 [address = "10.1.9.3"]
  }
  network vlan1_9 {
    address = "10.2.9.0/24"
    router0_9 [address = "10.2.9.1"]
    host1_1_9 [address = "10.2.9.2"]
    host1_2_9 [address = "10.2.9.3"]
  }
}
@endnwdiag
