@startnwdiag
nwdiag {
  network vlan0_3 {
    address = "10.1.3.0/24"
    host0_0_3 [address = "10.1.3.1"]
    host0_1_3 [address = "10.1.3.2"]
    host0_2_3 [address = "10.1.3.3"]
    host0_3_3 [address = "10.1.3.4"]
    host0_4_3 [address = "10.1.3.5"]
  }
  network vlan1_3 {
    address = "10.2.3.0/24"
    router0_3 [address = "10.2.3.1"]
    host1_1_3 [address = "10.2.3.2"]
    host1_2_3 [address = "10.2.3.3"]
    host1_3_3 [address = "10.2.3.4"]
    host1_4_3 [address = "10.2.3.5"]
  }
}
@endnwdiag
