@startnwdiag
nwdiag {
  network internet {
    address = "0.0.0.0/0"
    hq_vpn  [address = "1.2.3.4"]
    br1_vpn [address = "5.6.7.8"]
    br2_vpn [address = "9.10.11.12"]
  }
  network hq_lan {
    address = "10.1.0.0/24"
    hq_vpn   [address = "10.1.0.1"]
    hq_srv1  [address = "10.1.0.10"]
    hq_srv2  [address = "10.1.0.11"]
    hq_print [address = "10.1.0.50"]
  }
  network branch1 {
    address = "10.2.0.0/24"
    br1_vpn [address = "10.2.0.1"]
    br1_pc1 [address = "10.2.0.10"]
    br1_pc2 [address = "10.2.0.11"]
  }
  network branch2 {
    address = "10.3.0.0/24"
    br2_vpn [address = "10.3.0.1"]
    br2_pc1 [address = "10.3.0.10"]
  }
}
@endnwdiag
