@startnwdiag
nwdiag {
  network vlan0_13 {
    address = "10.1.3.0/24"
    host0_0_13 [address = "10.1.3.1"]
    host0_1_13 [address = "10.1.3.2"]
    host0_2_13 [address = "10.1.3.3"]
  }
  network vlan1_13 {
    address = "10.2.3.0/24"
    router0_13 [address = "10.2.3.1"]
    host1_1_13 [address = "10.2.3.2"]
    host1_2_13 [address = "10.2.3.3"]
  }
  network vlan2_13 {
    address = "10.3.3.0/24"
    router1_13 [address = "10.3.3.1"]
    host2_1_13 [address = "10.3.3.2"]
    host2_2_13 [address = "10.3.3.3"]
  }
}
@endnwdiag
