@startnwdiag
nwdiag {
  network vlan0_5 {
    address = "10.1.5.0/24"
    host0_0_5 [address = "10.1.5.1"]
    host0_1_5 [address = "10.1.5.2"]
    host0_2_5 [address = "10.1.5.3"]
  }
  network vlan1_5 {
    address = "10.2.5.0/24"
    router0_5 [address = "10.2.5.1"]
    host1_1_5 [address = "10.2.5.2"]
    host1_2_5 [address = "10.2.5.3"]
  }
  network vlan2_5 {
    address = "10.3.5.0/24"
    router1_5 [address = "10.3.5.1"]
    host2_1_5 [address = "10.3.5.2"]
    host2_2_5 [address = "10.3.5.3"]
  }
  network vlan3_5 {
    address = "10.4.5.0/24"
    router2_5 [address = "10.4.5.1"]
    host3_1_5 [address = "10.4.5.2"]
    host3_2_5 [address = "10.4.5.3"]
  }
}
@endnwdiag
