@startnwdiag
nwdiag {
  network vlan0_10 {
    address = "10.1.0.0/24"
    host0_0_10 [address = "10.1.0.1"]
    host0_1_10 [address = "10.1.0.2"]
    host0_2_10 [address = "10.1.0.3"]
    host0_3_10 [address = "10.1.0.4"]
  }
  network vlan1_10 {
    address = "10.2.0.0/24"
    router0_10 [address = "10.2.0.1"]
    host1_1_10 [address = "10.2.0.2"]
    host1_2_10 [address = "10.2.0.3"]
    host1_3_10 [address = "10.2.0.4"]
  }
  network vlan2_10 {
    address = "10.3.0.0/24"
    router1_10 [address = "10.3.0.1"]
    host2_1_10 [address = "10.3.0.2"]
    host2_2_10 [address = "10.3.0.3"]
    host2_3_10 [address = "10.3.0.4"]
  }
}
@endnwdiag
