@startuml
left to right direction
package CeruleanNodeAperture <<Node>> {
  class NodeApertureSource
}
package SaffronFrameAperture <<Frame>> {
  class FrameApertureSource
}
class RootApertureReceiver
NodeApertureSource --> RootApertureReceiver : node-exit
FrameApertureSource --> RootApertureReceiver : frame-exit
@enduml
