@startuml
left to right direction
node "Cerulean Node Aperture" {
  class NodeApertureSource
}
frame "Saffron Frame Aperture" {
  class FrameApertureSource
}
class RootApertureReceiver
NodeApertureSource --> RootApertureReceiver : node-exit
FrameApertureSource --> RootApertureReceiver : frame-exit
@enduml
