@startuml
skinparam packageStyle rectangle
package Host {
  package "Split Fallback" <<PreOne>> as SplitFallback $core <<PostTwo>> <<PostThree>> [[https://example.com/split{Split docs}]] #MistyRose {
    class SplitLeaf
  }
}
@enduml
