@startditaa
+----------+
|          |
|  Input   |
|          |
+----+-----+
     |
     v
+----+-----+
|          |
| Process  |
|          |
+----+-----+
     |
     v
+----+-----+
|          |
|  Output  |
|          |
+----------+
@endditaa
