@startditaa
   *---->-------+
   |            |
   |            v
   |         +------+
   |         |      |
   *----+    | Node |
   |    |    |      |
   v    v    +------+
+----+ +----+
|    | |    |
| A  | | B  |
|    | |    |
+----+ +----+
@endditaa
