@startditaa
           +--------+
           |        |
           | Router |
           |        |
           +---+----+
               |
    +----------+-----------+
    |          |           |
+---+--+   +---+--+   +---+--+
|      |   |      |   |      |
| PC 1 |   | PC 2 |   | PC 3 |
|      |   |      |   |      |
+------+   +------+   +------+
@endditaa
