@startditaa
  +--------+  +--------+  +--------+  +--------+  
  |        |  |        |  |        |  |        |  
  | Box1   |  | Box2   |  | Box3   |  | Box4   |  
  |        |  |        |  |        |  |        |  
  +--------+  +--------+  +--------+  +--------+  
@endditaa
