@startditaa
 /---------\      /---------\
 | cGRE    |      | cBLU    |
 | Service |----->| Cache   |
 | Layer   |      |         |
 \---------/      \---------/
      |
      v
 /---------\
 | cRED    |
 | Data    |
 | Store   |
 \---------/
@endditaa
