@startditaa
+--------+    +--------+
|        |    |        |
|  Opt A |....|  Opt B |
|        |    |        |
+--------+    +--------+
    :               :
    :               :
+--------+    +--------+
|        |    |        |
|  Opt C |    |  Opt D |
|        |    |        |
+--------+    +--------+
@endditaa
