@startditaa
+----------+----------+----------+----------+
| Name     | Type     | Size     | Nullable |
+----------+----------+----------+----------+
| id       | INT      | 4        | NO       |
+----------+----------+----------+----------+
| name     | VARCHAR  | 100      | NO       |
+----------+----------+----------+----------+
| email    | VARCHAR  | 200      | YES      |
+----------+----------+----------+----------+
| created  | DATETIME | 8        | NO       |
+----------+----------+----------+----------+
@endditaa
