@startditaa
+--------+ +--------+ +--------+
|{c}     | |{r}     | |{g}     |
|  Cyan  | |  Red   | | Green  |
+--------+ +--------+ +--------+

+--------+ +--------+
|{y}     | |{b}     |
| Yellow | |  Blue  |
+--------+ +--------+
@endditaa
