@startditaa
               +---------------+
               |               |
    Browser    |   Load Bal    |
 +----------+  |               |
 |          |->|  +----+----+  |
 |  Client  |  |  |LB1 |LB2 |  |
 |          |  |  +----+----+  |
 +----------+  +-------+-------+
                       |
       +---------------+---------------+
       |                               |
+------+------+                 +------+------+
|             |                 |             |
|  Web App 1  |                 |  Web App 2  |
|             |                 |             |
+------+------+                 +------+------+
       |                               |
       +---------------+---------------+
                       |
               +-------+-------+
               |               |
               |    Database   |
               |    Cluster    |
               |               |
               +---------------+
@endditaa
