@startuml
state SilentCurveEnvelope731 {
  [*] --> QuartzAlpha731
  QuartzAlpha731 --> QuartzBeta731
  QuartzBeta731 --> QuartzAlpha731
  QuartzBeta731 --> [*]
}
[*] --> SilentCurveEnvelope731
SilentCurveEnvelope731 --> [*]
@enduml
