@startuml
title User Retrieval with Cache
skinparam ParticipantPadding 20
hide footbox

participant "<<Component>>
Frontend" as FE
participant "<<Component>>
Backend" as BE
database "<<Database>>
Postgres" as PG
collections "<<Cache>>
Redis" as Redis

autonumber "<b>[0]"

FE -> BE : getUser(id)
activate BE #lightblue

BE -> Redis : get("user:" + id)
activate Redis #lightyellow
alt cache hit
  Redis --> BE : userData
  deactivate Redis
else cache miss
  deactivate Redis
  BE -> PG ++ : SELECT * FROM users WHERE id=?
  PG --> BE -- : row
  BE -> Redis ++ : set("user:" + id, userData, TTL=3600)
  Redis --> BE -- : OK
end

BE --> FE : User object
deactivate BE
@enduml
