@startuml
participant Z order 1
participant A order 5
participant M order 3
participant B order 2
participant Y order 4

A -> B : A to B
B -> M : B to M
M -> Y : M to Y
Y -> Z : Y to Z
Z -> A : Z to A (wrap)
@enduml
