@startuml
participant P0
participant P1
participant P2
participant P3
participant P4
participant P5
participant P6
participant P7
P0 -> P1 : msg 0
P1 -> P2 : msg 1
P2 -> P3 : msg 2
P3 -> P4 : msg 3
P4 -> P5 : msg 4
P5 -> P6 : msg 5
P6 -> P7 : msg 6
P7 -> P0 : msg 7
@enduml
