@startuml
Alice -> Bob : solid
Alice --> Bob : dotted
Alice ->> Bob : thin solid
Alice -->> Bob : thin dotted
Alice ->x Bob : lost
Alice <- Bob : back solid
Alice <-- Bob : back dotted
Alice <<- Bob : back thin
Alice <<-- Bob : back thin dotted
@enduml
