@startuml
participant ParticipantP
actor ActorP
boundary BoundaryP
control ControlP
entity EntityP
database DatabaseP
collections CollectionsP
queue QueueP
ParticipantP -> ActorP : msg 1
ActorP -> BoundaryP : msg 2
BoundaryP -> ControlP : msg 3
ControlP -> EntityP : msg 4
EntityP -> DatabaseP : msg 5
DatabaseP -> CollectionsP : msg 6
CollectionsP -> QueueP : msg 7
QueueP -> ParticipantP : msg 8
@enduml
