@startuml
skinparam monochrome true
skinparam shadowing false
skinparam ParticipantBorderThickness 1
participant Alice
participant Bob
participant Charlie
Alice -> Bob : request
note over Alice : note
Bob -> Charlie : delegate
Charlie --> Bob : result
Bob --> Alice : response
@enduml
