@startuml
Alice -> Bob : step 1
note left of Alice : note 1
note right of Bob : note 2
Bob -> Charlie : step 2
note over Bob : note 3
note over Charlie : note 4
Charlier --> Bob : step 3
note left of Bob : note 5
Bob --> Alice : step 4
note over Alice, Bob : note 6
@enduml
