@startuml
participant A
A -> B ++ #red : level 1
B -> C ++ #red : level 2
C -> D ++ #red : level 3
D -> E ++ #red : level 4
E --> D -- : return 4
D --> C -- : return 3
C --> B -- : return 2
B --> A -- : return 1
@enduml
