@startuml
P0 -> P1 ++ : call 1
rnote over P0 : before return 1
P1 -> P2 ++ : call 2
rnote over P1 : before return 2
P2 -> P3 ++ : call 3
rnote over P2 : before return 3
return result 3
return result 2
return result 1
@enduml
