@startuml
A -> B : start
opt cond1
  alt cond2
    loop cond3
      B -> C : deep
      C --> B : result
    end
    B --> A : g3 done
  else other2
  end
  B --> A : g2 done
end
B --> A : complete
@enduml
