@startuml
A -> B ++ : call level 1
B -> C ++ : call level 2
C -> D ++ : call level 3
D -> E ++ : call level 4
E -> F ++ : call level 5
return result level 5
return result level 4
return result level 3
return result level 2
return result level 1
@enduml
