@startuml
P0 --> P1 ++ #red : depth 1 dotted
P1 --> P2 ++ #blue : depth 2 dotted
P2 --> P3 ++ #red : depth 3 dotted
P3 --> P4 ++ #blue : depth 4 dotted
return return 4
return return 3
return return 2
return return 1
@enduml
