@startuml
A -> B : start
alt condition_0
opt condition_1
loop condition_2
par
  A -> B : par branch 3
and
critical condition_4
alt condition_5
opt condition_6
  B -> C : deep action
  C --> B : deep result
end
else alt_else
  B --> A : else
end
end
end
end
end
else alt_else
  B --> A : else
end
B --> A : done
@enduml
