@startuml
Alice -> Bob : page 1 message
Bob --> Alice : page 1 reply

newpage Page 2
Alice -> Bob : page 2 message
Bob --> Alice : page 2 reply

newpage Page 3
Alice -> Bob : page 3 message
Bob --> Alice : page 3 reply

newpage Page 4
Alice -> Bob : page 4 message
Bob --> Alice : page 4 reply
@enduml
