@startuml
Alice -> Bob ++ : start
alt success
  note over Bob : processing
  Bob -> DB ++ : query
  DB --> Bob -- : data
  Bob --> Alice -- : result
else error
  note right of Bob : error!
  Bob --> Alice -- : failure
end
@enduml
