@startuml
Alice -> Bob ++ : start
Bob -> C1 ++ : chain 1
Bob -> C2 ++ : chain 2
C1 -> D1 ++ : sub 1
C2 -> D2 ++ : sub 2
D1 --> C1 -- : done 1
D2 --> C2 -- : done 2
C1 --> Bob -- : chain 1 done
C2 --> Bob -- : chain 2 done
Bob --> Alice -- : all done
@enduml
