@startuml
participant Alice
participant Bob
Alice -> Bob : step 0
note over Alice : note 0
Bob --> Alice : reply 0
Alice -> Bob : step 1
note right of Bob : note 1
Bob --> Alice : reply 1
Alice -> Bob : step 2
note over Alice, Bob : over both 2
Bob --> Alice : reply 2
Alice -> Bob : step 3
note over Alice : note 3
Bob --> Alice : reply 3
Alice -> Bob : step 4
note right of Bob : note 4
Bob --> Alice : reply 4
Alice -> Bob : step 5
note over Alice, Bob : over both 5
Bob --> Alice : reply 5
Alice -> Bob : step 6
note over Alice : note 6
Bob --> Alice : reply 6
Alice -> Bob : step 7
note right of Bob : note 7
Bob --> Alice : reply 7
Alice -> Bob : step 8
note over Alice, Bob : over both 8
Bob --> Alice : reply 8
Alice -> Bob : step 9
note over Alice : note 9
Bob --> Alice : reply 9
Alice -> Bob : step 10
note right of Bob : note 10
Bob --> Alice : reply 10
Alice -> Bob : step 11
note over Alice, Bob : over both 11
Bob --> Alice : reply 11
Alice -> Bob : step 12
note over Alice : note 12
Bob --> Alice : reply 12
Alice -> Bob : step 13
note right of Bob : note 13
Bob --> Alice : reply 13
Alice -> Bob : step 14
note over Alice, Bob : over both 14
Bob --> Alice : reply 14
Alice -> Bob : step 15
note over Alice : note 15
Bob --> Alice : reply 15
Alice -> Bob : step 16
note right of Bob : note 16
Bob --> Alice : reply 16
Alice -> Bob : step 17
note over Alice, Bob : over both 17
Bob --> Alice : reply 17
Alice -> Bob : step 18
note over Alice : note 18
Bob --> Alice : reply 18
Alice -> Bob : step 19
note right of Bob : note 19
Bob --> Alice : reply 19
@enduml
