@startuml
Alice -> Bob : request
alt case A
  Bob --> Alice : result A
else case B
  Bob --> Alice : result B
else case C
  Bob --> Alice : result C
else default
  Bob --> Alice : default result
end
@enduml
