@startuml
Alice -> Bob : a
activate Bob
Bob -> Charlie : b
activate Charlie
Charlie -> Dave : c
activate Dave
Dave --> Charlie : d
deactivate Dave
Charlie --> Bob : e
deactivate Charlie
Bob --> Alice : f
deactivate Bob
@enduml
