@startuml
Alice -> Bob : request
alt async
  Bob -> External : call
  ...
  External --> Bob : callback
  Bob --> Alice : result
else sync
  Bob -> Internal : call
  Internal --> Bob : result
  Bob --> Alice : result
end
@enduml
