@startuml
participant Alice
participant Bob
Alice -> Bob : step 1
== Phase 1 ==
Bob --> Alice : reply 1
|||
Alice -> Bob : step 2
... pause 1 ...
Bob --> Alice : reply 2
|||
Alice -> Bob : step 3
== Phase 2 ==
Bob --> Alice : reply 3
|||
Alice -> Bob : step 4
... pause 3 ...
Bob --> Alice : reply 4
|||
Alice -> Bob : step 5
== Phase 3 ==
Bob --> Alice : reply 5
|||
Alice -> Bob : step 6
... pause 5 ...
Bob --> Alice : reply 6
|||
Alice -> Bob : step 7
== Phase 4 ==
Bob --> Alice : reply 7
|||
Alice -> Bob : step 8
... pause 7 ...
Bob --> Alice : reply 8
|||
@enduml
