@startuml
participant P00
participant P01
participant P02
participant P03
participant P04
participant P05
participant P06
participant P07
participant P08
participant P09
P00 -> P01 : step 1
P01 -> P02 : step 2
P02 -> P03 : step 3
P03 -> P04 : step 4
P04 -> P05 : step 5
P05 -> P06 : step 6
P06 -> P07 : step 7
P07 -> P08 : step 8
P08 -> P09 : step 9
P09 --> P08 : ret 1
P08 --> P07 : ret 2
P07 --> P06 : ret 3
P06 --> P05 : ret 4
P05 --> P04 : ret 5
P04 --> P03 : ret 6
P03 --> P02 : ret 7
P02 --> P01 : ret 8
P01 --> P00 : ret 9
@enduml
