@startuml
participant P00
participant P01
participant P02
participant P03
participant P04
participant P05
participant P06
participant P07
participant P08
participant P09
P00 -> P01 : msg 1
P01 -> P02 : msg 2
P02 -> P03 : msg 3
P03 -> P04 : msg 4
P04 -> P05 : msg 5
P05 -> P06 : msg 6
P06 -> P07 : msg 7
P07 -> P08 : msg 8
P08 -> P09 : msg 9
P09 -> P00 : msg 10
P00 -> P01 : msg 11
P01 -> P02 : msg 12
P02 -> P03 : msg 13
P03 -> P04 : msg 14
P04 -> P05 : msg 15
P05 -> P06 : msg 16
P06 -> P07 : msg 17
P07 -> P08 : msg 18
P08 -> P09 : msg 19
P09 -> P00 : msg 20
@enduml
