@startuml
hide footbox
box "Box 1"
  participant A0
  participant B0
end box
box "Box 2"
  participant A1
  participant B1
end box
box "Box 3"
  participant A2
  participant B2
end box

A0 -> B0 : msg 1
B0 --> A0 : reply 1
A1 -> B1 : msg 2
B1 --> A1 : reply 2
A2 -> B2 : msg 3
B2 --> A2 : reply 3
@enduml
