@startuml
skinparam DefaultFontName Arial
skinparam ParticipantBackgroundColor #003366
skinparam ParticipantFontColor white
skinparam SequenceArrowColor #003366
skinparam SequenceLifeLineBorderColor #003366
skinparam NoteBackgroundColor #E6EFF7
participant Alice
participant Bob
participant Charlie
Alice -> Bob : request
note over Alice : note
Bob -> Charlie : delegate
Charlie --> Bob : result
Bob --> Alice : response
@enduml
