@startuml
class Hub
class Spoke1
class Spoke2
class Spoke3
class Spoke4
class Spoke5
class Spoke6
class Spoke7
class Spoke8
class Spoke9
class Spoke10
Hub --> Spoke1
Hub --> Spoke2
Hub --> Spoke3
Hub --> Spoke4
Hub --> Spoke5
Hub --> Spoke6
Hub --> Spoke7
Hub --> Spoke8
Hub --> Spoke9
Hub --> Spoke10
@enduml
