@startuml
class Company {
  +String name
}
class Department {
  +String name
}
class Team {
  +String name
}
class Employee {
  +String name
  +String role
}
Company "1" o-- "1..*" Department
Department "1" o-- "1..*" Team
Team "1" o-- "1..*" Employee
@enduml
