@startuml
abstract class ReportGenerator {
  +void run()
  +{abstract} void readData()
  +{abstract} void formatData()
  +{abstract} void writeOutput()
}
class CsvReport {
  +void readData()
  +void formatData()
  +void writeOutput()
}
class PdfReport {
  +void readData()
  +void formatData()
  +void writeOutput()
}
class HtmlReport {
  +void readData()
  +void formatData()
  +void writeOutput()
}
ReportGenerator <|-- CsvReport
ReportGenerator <|-- PdfReport
ReportGenerator <|-- HtmlReport
@enduml
