@startuml
class N1
class N2
class N3
class N4
class N5
class N6
class N7
class N8
class N9
class N10
class N11
class N12
class N13
class N14
class N15
class N16
class N17
class N18
class N19
class N20
class N21
class N22
class N23
class N24
class N25
class N26
class N27
class N28
class N29
class N30
class N31
N1 --> N2
N1 --> N3
N2 --> N4
N2 --> N5
N3 --> N6
N3 --> N7
N4 --> N8
N4 --> N9
N5 --> N10
N5 --> N11
N6 --> N12
N6 --> N13
N7 --> N14
N7 --> N15
N8 --> N16
N8 --> N17
N9 --> N18
N9 --> N19
N10 --> N20
N10 --> N21
N11 --> N22
N11 --> N23
N12 --> N24
N12 --> N25
N13 --> N26
N13 --> N27
N14 --> N28
N14 --> N29
N15 --> N30
N15 --> N31
@enduml
