@startuml
class Level01 {
  +void m1()
}
class Level02 {
  +void m2()
}
class Level03 {
  +void m3()
}
class Level04 {
  +void m4()
}
Level01 <|-- Level02
Level02 <|-- Level03
Level03 <|-- Level04
interface Iface1
Level04 ..|> Iface1
@enduml
