@startuml
class MyClass {
  +void method()
}
abstract class MyAbstract {
  +{abstract} void method()
}
interface MyInterface {
  +void method()
}
enum MyEnum {
  VALUE1
  VALUE2
}
annotation MyAnnotation
entity MyEntity {
  *id : int
}
MyClass --|> MyAbstract
MyClass ..|> MyInterface
MyClass --> MyEnum
MyClass --> MyEntity
@enduml
