@startuml
interface Visitor {
  +void visitConcreteElementA(ConcreteElementA e)
  +void visitConcreteElementB(ConcreteElementB e)
}
interface Element {
  +void accept(Visitor v)
}
class ConcreteVisitor1 {
  +void visitConcreteElementA(ConcreteElementA e)
  +void visitConcreteElementB(ConcreteElementB e)
}
class ConcreteVisitor2 {
  +void visitConcreteElementA(ConcreteElementA e)
  +void visitConcreteElementB(ConcreteElementB e)
}
class ConcreteElementA {
  +void accept(Visitor v)
  +void operationA()
}
class ConcreteElementB {
  +void accept(Visitor v)
  +void operationB()
}
ConcreteVisitor1 ..|> Visitor
ConcreteVisitor2 ..|> Visitor
ConcreteElementA ..|> Element
ConcreteElementB ..|> Element
@enduml
