@startuml
interface Serializable {
  +byte[] serialize()
  +void deserialize(byte[] data)
}
class JsonSerializer {
  +byte[] serialize()
  +void deserialize(byte[] data)
}
class XmlSerializer {
  +byte[] serialize()
  +void deserialize(byte[] data)
}
class BinarySerializer {
  +byte[] serialize()
  +void deserialize(byte[] data)
}
JsonSerializer ..|> Serializable
XmlSerializer ..|> Serializable
BinarySerializer ..|> Serializable
@enduml
