@startuml
class Originator {
  -state: String
  +Memento save()
  +void restore(Memento m)
  +String getState()
}
class Memento {
  -state: String
  +String getState()
}
class Caretaker {
  -mementos: List<Memento>
  +void backup()
  +void undo()
}
Originator --> Memento : creates
Caretaker --> Originator
Caretaker o-- Memento
@enduml
