@startuml
class Base {
  +void method()
}
class Left {
  +void leftMethod()
}
class Right {
  +void rightMethod()
}
class Diamond {
  +void method()
}
Base <|-- Left
Base <|-- Right
Left <|-- Diamond
Right <|-- Diamond
@enduml
