@startuml
package controller {
  class UserController {
    +void handleRequest()
  }
}
package service {
  class UserService {
    +User getUser(int id)
  }
}
package dao {
  class UserDAO {
    +User findById(int id)
  }
}
package model {
  class User {
    +int id
    +String name
  }
}
controller.UserController ..> service.UserService
service.UserService ..> dao.UserDAO
dao.UserDAO ..> model.User
@enduml
