@startuml
interface I1 {
  +void method1()
}
interface I2 {
  +void method2()
}
interface I3 {
  +void method3()
}
interface I4 {
  +void method4()
}
interface I5 {
  +void method5()
}
interface I6 {
  +void method6()
}
interface I7 {
  +void method7()
}
interface I8 {
  +void method8()
}
class Impl
Impl ..|> I1
Impl ..|> I2
Impl ..|> I3
Impl ..|> I4
Impl ..|> I5
Impl ..|> I6
Impl ..|> I7
Impl ..|> I8
@enduml
