@startuml
abstract class Vehicle {
  +String make
  +String model
  +int year
  +void start()
  +void stop()
}
class Car {
  +int doors
  +void drive()
}
class Truck {
  +double payload
  +void haul()
}
class Motorcycle {
  +boolean hasSidecar
  +void ride()
}
class Bus {
  +int capacity
  +void pickUp()
}
class ElectricCar {
  +int batteryKWh
  +void charge()
}
class HybridCar {
  +double mpg
  +void switchMode()
}
class SportsCar {
  +int horsepower
  +void race()
}
class SUV {
  +boolean awd
  +void offroad()
}
Vehicle <|-- Car
Vehicle <|-- Truck
Vehicle <|-- Motorcycle
Vehicle <|-- Bus
Car <|-- ElectricCar
Car <|-- HybridCar
Car <|-- SportsCar
Car <|-- SUV
@enduml
