@startuml
class Level01 {
  +void method1()
}
class Level02 {
  +void method2()
}
class Level03 {
  +void method3()
}
class Level04 {
  +void method4()
}
class Level05 {
  +void method5()
}
class Level06 {
  +void method6()
}
class Level07 {
  +void method7()
}
class Level08 {
  +void method8()
}
class Level09 {
  +void method9()
}
class Level10 {
  +void method10()
}
Level01 <|-- Level02
Level02 <|-- Level03
Level03 <|-- Level04
Level04 <|-- Level05
Level05 <|-- Level06
Level06 <|-- Level07
Level07 <|-- Level08
Level08 <|-- Level09
Level09 <|-- Level10
@enduml
