@startuml
class Node1
class Node2
class Node3
class Node4
class Node5
class Node6
class Node7
class Node8
class Node9
class Node10
class Node11
class Node12
class Node13
class Node14
class Node15
class Node16
class Node17
class Node18
class Node19
class Node20
class Node21
class Node22
class Node23
class Node24
class Node25
Node1 --> Node2
Node2 --> Node3
Node3 --> Node4
Node4 --> Node5
Node5 --> Node6
Node6 --> Node7
Node7 --> Node8
Node8 --> Node9
Node9 --> Node10
Node10 --> Node11
Node11 --> Node12
Node12 --> Node13
Node13 --> Node14
Node14 --> Node15
Node15 --> Node16
Node16 --> Node17
Node17 --> Node18
Node18 --> Node19
Node19 --> Node20
Node20 --> Node21
Node21 --> Node22
Node22 --> Node23
Node23 --> Node24
Node24 --> Node25
@enduml
