@startuml
package user_service {
  class UserAPI
  class UserBusiness
  class UserData
  UserAPI ..> UserBusiness
  UserBusiness ..> UserData
}
package order_service {
  class OrderAPI
  class OrderBusiness
  class OrderData
  OrderAPI ..> OrderBusiness
  OrderBusiness ..> OrderData
}
package notification_service {
  class NotificationAPI
  class NotificationBusiness
  NotificationAPI ..> NotificationBusiness
}
package message_bus {
  class EventBus
  class EventPublisher
  class EventSubscriber
  EventPublisher --> EventBus
  EventSubscriber --> EventBus
}
user_service.UserBusiness ..> message_bus.EventPublisher : publishes UserCreated
order_service.OrderBusiness ..> message_bus.EventPublisher : publishes OrderPlaced
notification_service.NotificationBusiness ..> message_bus.EventSubscriber : subscribes
@enduml
