@startuml
class Level01 {
  +void m1()
}
class Level02 {
  +void m2()
}
class Level03 {
  +void m3()
}
class Level04 {
  +void m4()
}
class Level05 {
  +void m5()
}
Level01 <|-- Level02
Level02 <|-- Level03
Level03 <|-- Level04
Level04 <|-- Level05
interface Iface1
interface Iface2
interface Iface3
interface Iface4
Level05 ..|> Iface1
Level05 ..|> Iface2
Level05 ..|> Iface3
Level05 ..|> Iface4
@enduml
