@startuml
interface I1
interface I2
interface I3
interface I4
interface I5
abstract class A
abstract class B
class C
class D
class E
A <|-- B
B <|-- C
C <|-- D
D <|-- E
E ..|> I1
E ..|> I2
E ..|> I3
E ..|> I4
E ..|> I5
@enduml
