@startuml
abstract class Expression {
  +{abstract} int interpret(Context ctx)
}
class NumberExpression {
  -number: int
  +int interpret(Context ctx)
}
class AddExpression {
  -left: Expression
  -right: Expression
  +int interpret(Context ctx)
}
class SubtractExpression {
  -left: Expression
  -right: Expression
  +int interpret(Context ctx)
}
class MultiplyExpression {
  -left: Expression
  -right: Expression
  +int interpret(Context ctx)
}
class Context {
  -variables: Map<String, Integer>
  +int lookup(String name)
}
NumberExpression --|> Expression
AddExpression --|> Expression
SubtractExpression --|> Expression
MultiplyExpression --|> Expression
AddExpression o-- Expression
SubtractExpression o-- Expression
MultiplyExpression o-- Expression
@enduml
