@startuml
class Context {
  -state: State
  +void request()
  +void setState(State s)
}
abstract class State {
  +{abstract} void handle(Context ctx)
}
class ConcreteStateA {
  +void handle(Context ctx)
}
class ConcreteStateB {
  +void handle(Context ctx)
}
class ConcreteStateC {
  +void handle(Context ctx)
}
Context --> State
ConcreteStateA --|> State
ConcreteStateB --|> State
ConcreteStateC --|> State
@enduml
