@startuml
interface Iterable<T>
interface Collection<T>
interface List<T>
interface Set<T>
interface Queue<T>
interface Map<K,V>
abstract class AbstractCollection<T>
abstract class AbstractList<T>
abstract class AbstractSet<T>
class ArrayList<T>
class LinkedList<T>
class HashSet<T>
class TreeSet<T>
class HashMap<K,V>
class TreeMap<K,V>
Collection --|> Iterable
List --|> Collection
Set --|> Collection
Queue --|> Collection
AbstractCollection ..|> Collection
AbstractList --|> AbstractCollection
AbstractList ..|> List
AbstractSet --|> AbstractCollection
AbstractSet ..|> Set
ArrayList --|> AbstractList
LinkedList --|> AbstractList
LinkedList ..|> Queue
HashSet --|> AbstractSet
TreeSet --|> AbstractSet
HashMap ..|> Map
TreeMap ..|> Map
@enduml
