@startuml
class N1
class N2
class N3
class N4
class N5
class N6
class N7
class N8
class N9
class N10
N1 --> N2
N2 --> N3
N3 --> N4
N4 --> N5
N5 --> N6
N6 --> N7
N7 --> N8
N8 --> N9
N9 --> N10
@enduml
