@startuml
class ManyFields15 {
  +String field01
  +String field02
  +String field03
  +String field04
  +String field05
  +String field06
  +String field07
  +String field08
  +String field09
  +String field10
  +String field11
  +String field12
  +String field13
  +String field14
  +String field15
}
@enduml
