@startuml
class Ring1
class Ring2
class Ring3
class Ring4
class Ring5
class Ring6
class Ring7
class Ring8
class Ring9
class Ring10
Ring1 --> Ring2
Ring2 --> Ring3
Ring3 --> Ring4
Ring4 --> Ring5
Ring5 --> Ring6
Ring6 --> Ring7
Ring7 --> Ring8
Ring8 --> Ring9
Ring9 --> Ring10
Ring10 --> Ring1
@enduml
