@startuml
annotation RestController
annotation RequestMapping
annotation GetMapping
annotation PostMapping
annotation PathVariable
annotation RequestBody
annotation ResponseBody
class UserController <<RestController>> {
  <<RequestMapping("/users")>>
  +User getUser(int id)
  +User createUser(User u)
  +void deleteUser(int id)
}
@enduml
