@startuml
package top {
  class T1
  class T2
  class T3
  package mid {
    class M1
    class M2
    class M3
    package bottom {
      class B1
      class B2
      class B3
    }
  }
}
T1 --> M1
T2 --> M2
T3 --> M3
M1 --> B1
M2 --> B2
M3 --> B3
@enduml
