@startuml
class Parent {
  +void parentMethod()
}
class Child01
class Child02
class Child03
class Child04
class Child05
class Child06
class Child07
class Child08
class Child09
class Child10
Parent <|-- Child01
Parent <|-- Child02
Parent <|-- Child03
Parent <|-- Child04
Parent <|-- Child05
Parent <|-- Child06
Parent <|-- Child07
Parent <|-- Child08
Parent <|-- Child09
Parent <|-- Child10
@enduml
