@startuml
class Level01 {
  +void m1()
}
class Level02 {
  +void m2()
}
class Level03 {
  +void m3()
}
Level01 <|-- Level02
Level02 <|-- Level03
interface Iface1
interface Iface2
interface Iface3
Level03 ..|> Iface1
Level03 ..|> Iface2
Level03 ..|> Iface3
@enduml
