@startuml
class TypedMethods {
  +void voidReturn()
  +int intReturn()
  +long longReturn()
  +double doubleReturn()
  +boolean boolReturn()
  +String stringReturn()
  +Object objectReturn()
  +int[] arrayReturn()
  +List<String> listReturn()
}
@enduml
