@startuml
skinparam ClassBackgroundColor lightyellow
skinparam ClassBorderColor orange
skinparam ClassFontSize 14
skinparam ArrowColor darkgreen
skinparam ArrowThickness 2
class A {
  +void method()
}
class B {
  +String field
}
A --> B
@enduml
