@startuml
interface I1 {
  +void method1()
}
interface I2 {
  +void method2()
}
interface I3 {
  +void method3()
}
interface I4 {
  +void method4()
}
interface I5 {
  +void method5()
}
class Impl
Impl ..|> I1
Impl ..|> I2
Impl ..|> I3
Impl ..|> I4
Impl ..|> I5
@enduml
