@startuml
class Throwable {
  +String message
  +void printStackTrace()
}
class Exception
class RuntimeException
class Error
class IOException
class SQLException
class NullPointerException
class IllegalArgumentException
class IndexOutOfBoundsException
class OutOfMemoryError
class StackOverflowError
Throwable <|-- Exception
Throwable <|-- Error
Exception <|-- RuntimeException
Exception <|-- IOException
Exception <|-- SQLException
RuntimeException <|-- NullPointerException
RuntimeException <|-- IllegalArgumentException
RuntimeException <|-- IndexOutOfBoundsException
Error <|-- OutOfMemoryError
Error <|-- StackOverflowError
@enduml
