@startuml
class A {
  +void a()
}
class B {
  +void b()
}
class C {
  +void c()
}
A --> B : rel1
A --> C : rel2
B --> A : rel3
B --> C : rel4
C --> A : rel5
C --> B : rel6
A ..> B : dep1
A ..> C : dep2
@enduml
