@startuml
class Cls001 { +void m1() }
class Cls002 { +void m2() }
class Cls003 { +void m3() }
class Cls004 { +void m4() }
class Cls005 { +void m5() }
class Cls006 { +void m6() }
class Cls007 { +void m7() }
class Cls008 { +void m8() }
Cls001 --> Cls002
Cls002 --> Cls003
Cls003 --> Cls004
Cls004 --> Cls005
Cls005 --> Cls006
Cls006 --> Cls007
Cls007 --> Cls008
@enduml
