@startuml
class Level01 {
  +void method1()
}
class Level02 {
  +void method2()
}
class Level03 {
  +void method3()
}
class Level04 {
  +void method4()
}
class Level05 {
  +void method5()
}
Level01 <|-- Level02
Level02 <|-- Level03
Level03 <|-- Level04
Level04 <|-- Level05
@enduml
