@startuml
class Isolated01
class Isolated02
class Isolated03
class Isolated04
class Isolated05
class Isolated06
class Isolated07
class Isolated08
class Isolated09
class Isolated10
class Isolated11
class Isolated12
class Isolated13
class Isolated14
class Isolated15
@enduml
