@startuml
class PageClass1A
class PageClass1B
PageClass1A --> PageClass1B
newpage
class PageClass2A
class PageClass2B
PageClass2A --> PageClass2B
newpage
class PageClass3A
class PageClass3B
PageClass3A --> PageClass3B
@enduml
