@startuml
annotation Entity
annotation Table
annotation Id
annotation GeneratedValue
annotation Column
annotation OneToMany
annotation ManyToOne
class User <<Entity>> {
  <<Id>>
  <<GeneratedValue>>
  +int id
  <<Column(name="user_name")>>
  +String username
  <<Column(nullable=false)>>
  +String email
}
@enduml
