@startuml
class Class01 {
  +String field1
  +void method1()
}
class Class02 {
  +String field2
  +void method2()
}
class Class03 {
  +String field3
  +void method3()
}
class Class04 {
  +String field4
  +void method4()
}
class Class05 {
  +String field5
  +void method5()
}
class Class06 {
  +String field6
  +void method6()
}
class Class07 {
  +String field7
  +void method7()
}
class Class08 {
  +String field8
  +void method8()
}
class Class09 {
  +String field9
  +void method9()
}
class Class10 {
  +String field10
  +void method10()
}
class Class11 {
  +String field11
  +void method11()
}
class Class12 {
  +String field12
  +void method12()
}
class Class13 {
  +String field13
  +void method13()
}
class Class14 {
  +String field14
  +void method14()
}
class Class15 {
  +String field15
  +void method15()
}
class Class16 {
  +String field16
  +void method16()
}
class Class17 {
  +String field17
  +void method17()
}
class Class18 {
  +String field18
  +void method18()
}
class Class19 {
  +String field19
  +void method19()
}
class Class20 {
  +String field20
  +void method20()
}
class Class21 {
  +String field21
  +void method21()
}
class Class22 {
  +String field22
  +void method22()
}
class Class23 {
  +String field23
  +void method23()
}
class Class24 {
  +String field24
  +void method24()
}
class Class25 {
  +String field25
  +void method25()
}
class Class26 {
  +String field26
  +void method26()
}
class Class27 {
  +String field27
  +void method27()
}
class Class28 {
  +String field28
  +void method28()
}
class Class29 {
  +String field29
  +void method29()
}
class Class30 {
  +String field30
  +void method30()
}

Class01 --> Class02
Class02 --> Class03
Class03 --> Class04
Class04 --> Class05
Class05 --> Class06
Class06 --> Class07
Class07 --> Class08
Class08 --> Class09
Class09 --> Class10
Class10 --> Class11
Class11 --> Class12
Class12 --> Class13
Class13 --> Class14
Class14 --> Class15
Class15 --> Class16
Class16 --> Class17
Class17 --> Class18
Class18 --> Class19
Class19 --> Class20
Class20 --> Class21
Class21 --> Class22
Class22 --> Class23
Class23 --> Class24
Class24 --> Class25
Class25 --> Class26
Class26 --> Class27
Class27 --> Class28
Class28 --> Class29
Class29 --> Class30
@enduml
