@startuml
class A {
  +void methodA()
}
class B {
  +void methodB()
}
class C {
  +void methodC()
}
class D {
  +void methodD()
}
class E {
  +void methodE()
}
A <|-- B
B <|-- C
C <|-- D
D <|-- E
@enduml
