@startuml
class MyClass
note right of MyClass
  Line 1: some documentation text here
  Line 2: some documentation text here
  Line 3: some documentation text here
  Line 4: some documentation text here
  Line 5: some documentation text here
  Line 6: some documentation text here
  Line 7: some documentation text here
  Line 8: some documentation text here
  Line 9: some documentation text here
  Line 10: some documentation text here
  Line 11: some documentation text here
  Line 12: some documentation text here
  Line 13: some documentation text here
  Line 14: some documentation text here
  Line 15: some documentation text here
  Line 16: some documentation text here
  Line 17: some documentation text here
  Line 18: some documentation text here
  Line 19: some documentation text here
  Line 20: some documentation text here
end note
@enduml
