@startuml
class R1C1
class R1C2
class R1C3
class R1C4
class R2C1
class R2C2
class R2C3
class R2C4
class R3C1
class R3C2
class R3C3
class R3C4
R1C1 --> R1C2
R1C2 --> R1C3
R1C3 --> R1C4
R2C1 --> R2C2
R2C2 --> R2C3
R2C3 --> R2C4
R3C1 --> R3C2
R3C2 --> R3C3
R3C3 --> R3C4
R1C1 --> R2C1
R1C2 --> R2C2
R1C3 --> R2C3
R1C4 --> R2C4
R2C1 --> R3C1
R2C2 --> R3C2
R2C3 --> R3C3
R2C4 --> R3C4
@enduml
