@startuml
class AllModifiers {
  +publicField: String
  -privateField: int
  #protectedField: double
  ~packageField: boolean
  {static} +staticPublicField: String
  {static} -staticPrivateField: int
  +publicMethod(): void
  -privateMethod(): void
  #protectedMethod(): void
  ~packageMethod(): void
  {static} +staticPublicMethod(): void
  {static} -staticPrivateMethod(): void
}
@enduml
