@startuml
class Context {
  -strategy: Strategy
  +void setStrategy(Strategy s)
  +void executeStrategy()
}
interface Strategy {
  +void execute()
}
class ConcreteStrategyA {
  +void execute()
}
class ConcreteStrategyB {
  +void execute()
}
class ConcreteStrategyC {
  +void execute()
}
Context --> Strategy
ConcreteStrategyA ..|> Strategy
ConcreteStrategyB ..|> Strategy
ConcreteStrategyC ..|> Strategy
@enduml
