@startuml
class Source
class Target1
class Target2
class Target3
class Target4
class Target5
class Target6
Source <|-- Target1
Source ..|> Target2
Source *-- Target3
Source o-- Target4
Source --> Target5
Source ..> Target6
@enduml
