@startuml
package Outer {
  interface IOuter
  package Inner {
    interface IInner
    component CoreComp
    CoreComp - IInner
  }
  component OuterComp
  OuterComp - IOuter
  Inner --> OuterComp
}
@enduml
