@startuml
package Dense {
  component M1
  component M2
  component M3
  component M4
  component M5
  component M6
}
M1 --> M2
M1 --> M3
M1 --> M4
M1 --> M5
M1 --> M6
M2 --> M3
M2 --> M4
M2 --> M5
M2 --> M6
M3 --> M4
M3 --> M5
M3 --> M6
M4 --> M5
M4 --> M6
M5 --> M6
@enduml
