@startuml
component C01
component C02
component C03
component C04
component C05
component C06
component C07
component C08
component C09
component C10
component C11
component C12
component C13
component C14
component C15
component C16
component C17
component C18
component C19
component C20
C01 --> C02
C02 --> C03
C03 --> C04
C04 --> C05
C05 --> C06
C06 --> C07
C07 --> C08
C08 --> C09
C09 --> C10
C10 --> C11
C11 --> C12
C12 --> C13
C13 --> C14
C14 --> C15
C15 --> C16
C16 --> C17
C17 --> C18
C18 --> C19
C19 --> C20
C20 --> C01
@enduml
