@startuml
component C01
component C02
component C03
component C04
component C05
component C06
component C07
component C08
C01 --> C02
C02 --> C03
C03 --> C04
C04 --> C05
C05 --> C06
C06 --> C07
C07 --> C08
@enduml
