@startuml
frame "Request Processing" {
  component Validator
  component Processor
  component Formatter
  Validator --> Processor
  Processor --> Formatter
}
frame "Data Access" {
  component DAO
  database DB
  DAO --> DB
}
Formatter --> DAO
@enduml
