@startuml
component Router {
  portin pIn1
  portin pIn2
  portout pOut1
  portout pOut2
}
component Sender1
component Sender2
component Receiver1
component Receiver2
Sender1 --> Router::pIn1
Sender2 --> Router::pIn2
Router::pOut1 --> Receiver1
Router::pOut2 --> Receiver2
@enduml
