@startuml
folder "src" {
  folder "controllers" {
    component UserController
    component ProductController
  }
  folder "services" {
    component UserService
    component ProductService
  }
  folder "models" {
    component User
    component Product
  }
}
UserController --> UserService
ProductController --> ProductService
UserService --> User
ProductService --> Product
@enduml
