@startuml
package Group1 {
  component Svc1
  component Svc2
  component Svc3
  component Svc4
  component Svc5
  component Svc6
}
Svc1 --> Svc2
Svc2 --> Svc3
Svc3 --> Svc4
Svc4 --> Svc5
Svc5 --> Svc6
@enduml
