@startgantt
[Task Alice] on {Alice} lasts 9 days
[Task Bob] on {Bob} lasts 2 days
[Task Bob] starts at [Task Alice]'s end
[Task Charlie] on {Charlie} lasts 3 days
[Task Charlie] starts at [Task Bob]'s end
@endgantt
