@startgantt
Project starts 2024-01-01
saturday are closed
sunday are closed
[Task 1] lasts 5 days
[Task 2] lasts 5 days
[Task 2] starts at [Task 1]'s end
[Task 3] lasts 5 days
[Task 3] starts at [Task 2]'s end
@endgantt
