@startgantt
Project starts 2024-01-01
saturday are closed
sunday are closed
[Auth] lasts 8 days
[Auth] is colored in Coral
[Dashboard] lasts 11 days
[Dashboard] is colored in LightBlue
[Dashboard] starts at [Auth]'s end
[Reports] lasts 14 days
[Reports] is colored in LightGreen
[Reports] starts at [Dashboard]'s end
[Search] lasts 17 days
[Search] is colored in Gold
[Search] starts at [Reports]'s end
[Notifications] lasts 20 days
[Notifications] is colored in Plum
[Notifications] starts at [Search]'s end
@endgantt
