@startgantt
[Phase 1] lasts 10 days
[Milestone 1] happens at [Phase 1]'s end
[Phase 2] lasts 10 days
[Phase 2] starts at [Milestone 1]'s end
[Milestone 2] happens at [Phase 2]'s end
[Phase 3] lasts 5 days
[Phase 3] starts at [Milestone 2]'s end
[Project Complete] happens at [Phase 3]'s end
@endgantt
