@startgantt
Project starts 2024-06-01

section Phase 1
[P0T0] lasts 20 days
[P0T1] lasts 24 days
[P0T1] starts at [P0T0]'s end
[Milestone 1] happens at [P0T1]'s end

section Phase 2
[P1T0] lasts 24 days
[P1T0] starts at [P0T1]'s end
[P1T1] lasts 28 days
[P1T1] starts at [P1T0]'s end
[Milestone 2] happens at [P1T1]'s end

section Phase 3
[P2T0] lasts 28 days
[P2T0] starts at [P1T1]'s end
[P2T1] lasts 32 days
[P2T1] starts at [P2T0]'s end
[Milestone 3] happens at [P2T1]'s end

section Phase 4
[P3T0] lasts 32 days
[P3T0] starts at [P2T1]'s end
[P3T1] lasts 36 days
[P3T1] starts at [P3T0]'s end
[Milestone 4] happens at [P3T1]'s end

@endgantt
