@startgantt
[T1] lasts 6 days
[T1] is 0% completed
[T1] is colored in Coral
[T2] lasts 9 days
[T2] is 20% completed
[T2] is colored in LightGreen
[T2] starts at [T1]'s end
[T3] lasts 12 days
[T3] is 40% completed
[T3] is colored in Gold
[T3] starts at [T2]'s end
[T4] lasts 15 days
[T4] is 60% completed
[T4] is colored in Plum
[T4] starts at [T3]'s end
[T5] lasts 18 days
[T5] is 80% completed
[T5] is colored in LightBlue
[T5] starts at [T4]'s end
@endgantt
