@startgantt
Project starts 2024-01-01

section Section 1
[T0_0] lasts 4 days
[T0_1] lasts 8 days
[T0_1] starts at [T0_0]'s end
-- Checkpoint --

section Section 2
[T1_0] lasts 8 days
[T1_0] starts at [T0_1]'s end
[T1_1] lasts 12 days
[T1_1] starts at [T1_0]'s end
-- Checkpoint --

@endgantt
