@startgantt
Project starts 2024-01-01
[M0] happens 2024-01-01
[Phase1] lasts 10 days
[M1] happens at [Phase1]'s end
[Phase2] lasts 15 days
[Phase2] starts at [Phase1]'s end
[M2] happens at [Phase2]'s end

@endgantt
