@startgantt
Project starts 2024-01-01

section Phase 1
[P0T0] lasts 20 days
[P0T1] lasts 24 days
[P0T1] starts at [P0T0]'s end
[Milestone 1] happens at [P0T1]'s end

section Phase 2
[P1T0] lasts 24 days
[P1T0] starts at [P0T1]'s end
[P1T1] lasts 28 days
[P1T1] starts at [P1T0]'s end
[Milestone 2] happens at [P1T1]'s end

@endgantt
