@startgantt
[Task A] lasts 5 days
[Task A] is colored in Coral
[Task B] lasts 7 days
[Task B] is colored in LightBlue
[Task C] lasts 4 days
[Task C] is colored in LightGreen
[Task D] lasts 6 days
[Task D] is colored in Gold
@endgantt
