@startuml
skinparam linetype polyline
class Controller
class Service
class Repository
class Model
class View
class DTO
Controller --> Service
Controller --> View
Service --> Repository
Service --> DTO
Repository --> Model
DTO --> Model

@enduml
