@startuml
set namespaceSeparator ::
left to right direction
package NoteQuarkReviewArchiveA {
  class NoteQuarkReviewTargetA
}
package NoteQuarkReviewArchiveA {
  note "separator note body 8511" as NoteQuarkReviewMemoA
}
NoteQuarkReviewArchiveA::NoteQuarkReviewMemoA .. NoteQuarkReviewArchiveA::NoteQuarkReviewTargetA
@enduml
