@startuml
class StereotypeAnchor9001
package "Stereotype Folder 9003" <<folder>> {
}
package "Stereotype Frame 9005" <<frame>> {
}
package "Stereotype Node 9007" <<node>> {
}
package "Stereotype Database 9009" <<database>> {
}
package "Stereotype Rectangle 9011" <<rectangle>> {
}
package "Stereotype Cloud 9013" <<cloud>> {
}
package "Stereotype Ordinary 9015" <<Application>> {
}
package FilledNeighbor9017 {
  class FilledLeaf9019
}
class StereotypeTail9021
StereotypeAnchor9001 --> StereotypeTail9021
@enduml
