@startuml
robust "Sig0" as s0
robust "Sig1" as s1
robust "Sig2" as s2
robust "Sig3" as s3
robust "Sig4" as s4
highlight 100 to 200 #lightyellow : phase 3
@0
s0 is idle
s1 is active
s2 is active
s3 is idle
s4 is active
@100
s0 is active
s1 is active
s2 is idle
s3 is active
s4 is active
@200
s0 is active
s1 is idle
s2 is active
s3 is active
s4 is idle
@300
s0 is idle
s1 is active
s2 is active
s3 is idle
s4 is active
@400
s0 is active
s1 is active
s2 is idle
s3 is active
s4 is active

@enduml
