@startuml
robust "R0_14" as r0_14
robust "R1_14" as r1_14
robust "R2_14" as r2_14
concise "C0_14" as c0_14
binary "B0_14" as b0_14
@0
r0_14 is active
r1_14 is idle
r2_14 is active
c0_14 is free
b0_14 is high
@100
r0_14 is idle
r1_14 is active
r2_14 is idle
c0_14 is busy
b0_14 is low
@200
r0_14 is active
r1_14 is idle
r2_14 is active
c0_14 is busy
b0_14 is high
@300
r0_14 is idle
r1_14 is active
r2_14 is idle
c0_14 is free
b0_14 is low

@enduml
