@startuml
robust "R0_5" as r0_5
robust "R1_5" as r1_5
robust "R2_5" as r2_5
concise "C0_5" as c0_5
concise "C1_5" as c1_5
binary "B0_5" as b0_5
binary "B1_5" as b1_5
@0
r0_5 is active
r1_5 is idle
r2_5 is active
c0_5 is free
c1_5 is busy
b0_5 is high
b1_5 is low
@100
r0_5 is idle
r1_5 is active
r2_5 is idle
c0_5 is busy
c1_5 is busy
b0_5 is low
b1_5 is high
@200
r0_5 is active
r1_5 is idle
r2_5 is active
c0_5 is busy
c1_5 is free
b0_5 is high
b1_5 is low
@300
r0_5 is idle
r1_5 is active
r2_5 is idle
c0_5 is free
c1_5 is busy
b0_5 is low
b1_5 is high

@enduml
