@startuml
title System Boot Sequence
scale 1 as 50 pixels
robust "Power" as pwr
robust "Clock" as clk
concise "Firmware" as fw
@0
pwr is off
clk is stopped
fw is unknown
@100
pwr is on
@150
clk is running
@200
fw is loading
@400
fw is running
@enduml
