@startuml
binary "Sig0" as s0
binary "Sig1" as s1
binary "Sig2" as s2
@0
s0 is high
s1 is low
s2 is high
@100
s0 is low
s1 is high
s2 is low
@200
s0 is high
s1 is low
s2 is high
@300
s0 is low
s1 is high
s2 is low

@enduml
