@startuml
robust "R0_9" as r0_9
concise "C0_9" as c0_9
concise "C1_9" as c1_9
binary "B0_9" as b0_9
binary "B1_9" as b1_9
@0
r0_9 is active
c0_9 is free
c1_9 is busy
b0_9 is high
b1_9 is low
@100
r0_9 is idle
c0_9 is busy
c1_9 is busy
b0_9 is low
b1_9 is high
@200
r0_9 is active
c0_9 is busy
c1_9 is free
b0_9 is high
b1_9 is low
@300
r0_9 is idle
c0_9 is free
c1_9 is busy
b0_9 is low
b1_9 is high

@enduml
