@startuml
robust "R0_1" as r0_1
robust "R1_1" as r1_1
concise "C0_1" as c0_1
concise "C1_1" as c1_1
binary "B0_1" as b0_1
binary "B1_1" as b1_1
@0
r0_1 is active
r1_1 is idle
c0_1 is free
c1_1 is busy
b0_1 is high
b1_1 is low
@100
r0_1 is idle
r1_1 is active
c0_1 is busy
c1_1 is busy
b0_1 is low
b1_1 is high
@200
r0_1 is active
r1_1 is idle
c0_1 is busy
c1_1 is free
b0_1 is high
b1_1 is low
@300
r0_1 is idle
r1_1 is active
c0_1 is free
c1_1 is busy
b0_1 is low
b1_1 is high

@enduml
