@startuml
concise "Sig0" as s0
concise "Sig1" as s1
concise "Sig2" as s2
concise "Sig3" as s3
@0
s0 is idle
s1 is active
s2 is waiting
s3 is error
@100
s0 is active
s1 is waiting
s2 is error
s3 is idle
@200
s0 is waiting
s1 is error
s2 is idle
s3 is active
@300
s0 is error
s1 is idle
s2 is active
s3 is waiting

@enduml
