@startuml
robust "R0_10" as r0_10
robust "R1_10" as r1_10
concise "C0_10" as c0_10
binary "B0_10" as b0_10
@0
r0_10 is active
r1_10 is idle
c0_10 is free
b0_10 is high
@100
r0_10 is idle
r1_10 is active
c0_10 is busy
b0_10 is low
@200
r0_10 is active
r1_10 is idle
c0_10 is busy
b0_10 is high
@300
r0_10 is idle
r1_10 is active
c0_10 is free
b0_10 is low

@enduml
