@startuml
robust "Master" as m
robust "Slave" as s
binary "ACK" as ack
@0
m is idle
s is idle
ack is low
@50
m is sending
@100
s is receiving
@150
ack is high
m is waiting
@200
ack is low
m is idle
s is processing
@300
s is idle
@enduml
