@startuml
concise "P0" as p0
concise "P1" as p1
concise "P2" as p2
concise "P3" as p3
concise "P4" as p4
concise "P5" as p5
concise "P6" as p6
concise "P7" as p7
@0
p0 is active
p1 is idle
p2 is idle
p3 is idle
p4 is idle
p5 is idle
p6 is idle
p7 is idle
@100
p0 is idle
p1 is active
p2 is idle
p3 is idle
p4 is idle
p5 is idle
p6 is idle
p7 is idle
@200
p0 is idle
p1 is idle
p2 is active
p3 is idle
p4 is idle
p5 is idle
p6 is idle
p7 is idle
@300
p0 is idle
p1 is idle
p2 is idle
p3 is active
p4 is idle
p5 is idle
p6 is idle
p7 is idle

@enduml
