@startuml
robust "R0_7" as r0_7
robust "R1_7" as r1_7
concise "C0_7" as c0_7
concise "C1_7" as c1_7
binary "B0_7" as b0_7
binary "B1_7" as b1_7
@0
r0_7 is active
r1_7 is idle
c0_7 is free
c1_7 is busy
b0_7 is high
b1_7 is low
@100
r0_7 is idle
r1_7 is active
c0_7 is busy
c1_7 is busy
b0_7 is low
b1_7 is high
@200
r0_7 is active
r1_7 is idle
c0_7 is busy
c1_7 is free
b0_7 is high
b1_7 is low
@300
r0_7 is idle
r1_7 is active
c0_7 is free
c1_7 is busy
b0_7 is low
b1_7 is high

@enduml
