@startuml
binary "Sig0" as s0
binary "Sig1" as s1
binary "Sig2" as s2
binary "Sig3" as s3
@0
s0 is high
s1 is low
s2 is high
s3 is low
@100
s0 is low
s1 is high
s2 is low
s3 is high
@200
s0 is high
s1 is low
s2 is high
s3 is low
@300
s0 is low
s1 is high
s2 is low
s3 is high

@enduml
