@startmindmap
*[#orange] Root 14
**[#cyan] Node d2
***[#violet] Node d3
****[#lightblue] Node d4
*****[#lightgreen] Node d5
** Extra right
***_ No box
-- Left branch
---[#violet] Colored left
@endmindmap
