@startmindmap
*[#pink] Root 5
**[#violet] Branch A
***[#lightgreen] Leaf A1
***_ No box leaf
**[#violet] Branch B
*** Leaf B1
**_ Branch no box
*** Sub leaf
-- Left 5
---[#lightgreen] Left child
@endmindmap
