@startmindmap
*[#lightgreen] Root 19
**[#blue] Branch A
***[#yellow] Leaf A1
***_ No box leaf
**[#blue] Branch B
*** Leaf B1
**_ Branch no box
*** Sub leaf
-- Left 19
---[#yellow] Left child
@endmindmap
