@startuml
top to bottom direction
skinparam linetype ortho

class LateDependencySource
class LateDependencyTarget
class LateUpperOne
class LateUpperTwo
class LateLowerOne
class LateLowerTwo

LateUpperOne --> LateUpperTwo
LateLowerOne --> LateLowerTwo
LateDependencySource --> LateUpperOne
LateLowerTwo --> LateDependencyTarget
LateDependencySource <-- LateDependencyTarget
@enduml
