import java.awt.*;
import java.awt.font.FontRenderContext;
import java.io.*;
import java.nio.file.*;
import java.util.*;
public class GenW {
  static double w(Font f, FontRenderContext frc, int c){
    return f.getStringBounds(new String(Character.toChars(c)), frc).getWidth();
  }
  public static void main(String[] a) throws Exception {
    FontRenderContext frc = new FontRenderContext(null, true, true);
    Font p=new Font("SansSerif",Font.PLAIN,14), b=new Font("SansSerif",Font.BOLD,14);
    java.util.List<String> lines = Files.readAllLines(Paths.get("/tmp/cps.txt"));
    StringBuilder sb=new StringBuilder();
    sb.append("// Generated by /tmp/GenW.java via java.awt.FontMetrics (JVM SansSerif logical font,\n");
    sb.append("// the same engine PlantUML measures SVG text with). Values are advance-per-unit-size\n");
    sb.append("// (advance at size 14 / 14); multiply by font_size. (codepoint, plain, bold).\n");
    sb.append("pub(crate) const NON_ASCII_WIDTHS: &[(u32, f64, f64)] = &[\n");
    for(String ln:lines){ if(ln.isBlank()) continue;
      int c=Integer.parseInt(ln.trim());
      sb.append(String.format("    (%d, %.15e, %.15e),%n", c, w(p,frc,c)/14.0, w(b,frc,c)/14.0));
    }
    sb.append("];\n");
    Files.write(Paths.get("/tmp/non_ascii_widths.rs"), sb.toString().getBytes());
    System.out.println("emitted "+lines.size()+" entries to /tmp/non_ascii_widths.rs");
  }
}
