@startuml
left to right direction
skinparam stateFontName Times New Roman
skinparam stateFontStyle plain
skinparam stateFontSize 16
skinparam stateArrowFontName Times New Roman
skinparam stateArrowFontStyle plain
skinparam stateArrowFontSize 14

state "Base P4" as P4
P4 : plain **Bold7** //Italic8// **//Both9!?//**
state "Target R6" as R6
P4 --> R6 : plain **Bold2** //Italic3// **//Both4!?//**
R6 --> R6 : self **B5** plus //I6//
@enduml
