@startuml
cloud "Origin" {
  node "Origin Server"
  storage "Asset Storage"
  "Origin Server" --> "Asset Storage"
}
cloud "CDN Network" {
  node "PoP US-East"
  node "PoP EU-West"
  node "PoP AP-South"
  node "PoP US-West"
}
"Origin Server" --> "PoP US-East" : push
"Origin Server" --> "PoP EU-West" : push
"Origin Server" --> "PoP AP-South" : push
"Origin Server" --> "PoP US-West" : push
node "End User US"
node "End User EU"
node "End User AP"
"End User US" --> "PoP US-East" : request
"End User EU" --> "PoP EU-West" : request
"End User AP" --> "PoP AP-South" : request
@enduml
