@startuml
node Service1
node Service2
node Service3
node Service4
node Service5
Service1 --> Service2
Service1 --> Service3
Service2 --> Service3
Service2 --> Service4
Service3 --> Service4
Service3 --> Service5
Service4 --> Service5
@enduml
