@startuml
cloud "Region 1" {
  node "App-1"
  database "DB-1"
  "App-1" --> "DB-1"
}
cloud "Region 2" {
  node "App-2"
  database "DB-2"
  "App-2" --> "DB-2"
}
"DB-1" --> "DB-2" : replication
@enduml
