@startuml
node Server1 {
  artifact app1.jar
}
node Server2 {
  artifact app2.jar
}
node Server3 {
  artifact app3.jar
}
node Server4 {
  artifact app4.jar
}
Server1 --> Server2 : sync
Server2 --> Server3 : sync
Server3 --> Server4 : sync
@enduml
