@startuml
database Primary
database Replica1
database Replica2
database Replica3
database Replica4
Primary --> Replica1 : replication
Primary --> Replica2 : replication
Primary --> Replica3 : replication
Primary --> Replica4 : replication
@enduml
