@startuml
node Producer
queue "Message Queue" as MQ
node Consumer1
node Consumer2
node Consumer3
Producer --> MQ : publish
MQ --> Consumer1 : subscribe
MQ --> Consumer2 : subscribe
MQ --> Consumer3 : subscribe
@enduml
