@startuml
node Hub
node Spoke1
node Spoke2
node Spoke3
node Spoke4
node Spoke5
node Spoke6
node Spoke7
node Spoke8
Hub --> Spoke1
Hub --> Spoke2
Hub --> Spoke3
Hub --> Spoke4
Hub --> Spoke5
Hub --> Spoke6
Hub --> Spoke7
Hub --> Spoke8
@enduml
