@startuml
node "Web Tier" {
  node WebServer1 <<Apache>>
  node WebServer2 <<Apache>>
}
node "App Tier" {
  node AppServer1 <<Tomcat>>
  node AppServer2 <<Tomcat>>
}
node "Data Tier" {
  database PrimaryDB <<MySQL>>
  database ReplicaDB <<MySQL>>
}
WebServer1 --> AppServer1 : HTTP
WebServer2 --> AppServer2 : HTTP
AppServer1 --> PrimaryDB : JDBC
AppServer2 --> PrimaryDB : JDBC
PrimaryDB --> ReplicaDB : replication
@enduml
