@startuml
node EventSource
queue "Topic A" as TA
queue "Topic B" as TB
queue "Dead Letter Queue" as DLQ
node HandlerA1
node HandlerA2
node HandlerB1
EventSource --> TA
EventSource --> TB
TA --> HandlerA1
TA --> HandlerA2
TB --> HandlerB1
HandlerA1 --> DLQ : on error
@enduml
