@startuml
node "K8s Cluster" {
  node "Worker Node" {
    node "Pod-1" {
      component "Container-1"
    }
    node "Pod-2" {
      component "Container-2"
    }
    node "Pod-3" {
      component "Container-3"
    }
    node "Pod-4" {
      component "Container-4"
    }
  }
  node "Master" {
    component "API Server"
    database "etcd"
  }
}
@enduml
