// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0
//
// Extract Java AWT line metrics and printable-ASCII advances for a physical
// font using PlantUML's Graphics2D rendering hints.
//
// Usage:
//   javac tools/PhysicalFontMetricsExtract.java -d /tmp
//   java -Djava.awt.headless=true -cp /tmp PhysicalFontMetricsExtract "Courier New"

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.font.LineMetrics;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.util.Arrays;

public class PhysicalFontMetricsExtract {

    static Graphics2D graphics() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics = image.createGraphics();
        graphics.setRenderingHint(
            RenderingHints.KEY_TEXT_ANTIALIASING,
            RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        graphics.setRenderingHint(
            RenderingHints.KEY_FRACTIONALMETRICS,
            RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        return graphics;
    }

    public static void main(String[] args) {
        if (args.length == 2 && args[1].equals("--rust-unicode-ranges")) {
            emitRustUnicodeRanges(args[0]);
            return;
        }
        if (args.length != 1) {
            throw new IllegalArgumentException(
                "expected a physical font family and optional --rust-unicode-ranges");
        }
        Graphics2D graphics = graphics();
        int[] sizes = {10, 11, 12, 13, 14, 16, 21};
        int[] styles = {Font.PLAIN, Font.BOLD, Font.ITALIC, Font.BOLD | Font.ITALIC};

        for (int size : sizes) {
            for (int style : styles) {
                Font font = new Font(args[0], style, size);
                FontMetrics metrics = graphics.getFontMetrics(font);
                LineMetrics line = metrics.getLineMetrics("M", graphics);
                Rectangle2D advance = metrics.getStringBounds("M", graphics);
                System.out.printf(
                    "requested=%s resolved=%s size=%d style=%d advance=%s ascent=%s descent=%s height=%s%n",
                    args[0],
                    font.getFamily(),
                    size,
                    style,
                    repr(advance.getWidth()),
                    repr(line.getAscent()),
                    repr(line.getDescent()),
                    repr(line.getHeight()));
            }
        }

        int unitsPerEm = 2048;
        for (int style : styles) {
            Font font = new Font(args[0], style, unitsPerEm);
            FontMetrics metrics = graphics.getFontMetrics(font);
            StringBuilder units = new StringBuilder();
            for (char c = 32; c <= 126; c++) {
                if (units.length() > 0) {
                    units.append(',');
                }
                units.append(Math.round(metrics.getStringBounds(
                    Character.toString(c), graphics).getWidth()));
            }
            LineMetrics line = metrics.getLineMetrics("M", graphics);
            System.out.printf(
                "table requested=%s resolved=%s style=%d unitsPerEm=%d ascent=%d descent=%d height=%d%n%s%n",
                args[0],
                font.getFamily(),
                style,
                unitsPerEm,
                Math.round(line.getAscent()),
                Math.round(line.getDescent()),
                Math.round(line.getHeight()),
                units);
        }
        graphics.dispose();
    }

    static void emitRustUnicodeRanges(String family) {
        Graphics2D graphics = graphics();
        int unitsPerEm = 2048;
        long fractionalScale = 65536;
        int[] styles = {Font.PLAIN, Font.BOLD, Font.ITALIC, Font.BOLD | Font.ITALIC};
        FontMetrics[] metrics = new FontMetrics[styles.length];
        for (int i = 0; i < styles.length; i++) {
            metrics[i] = graphics.getFontMetrics(new Font(family, styles[i], unitsPerEm));
        }

        int undefinedCodepoint = 0x0378;
        long[] missingUnits = scalarFixedUnits(metrics, undefinedCodepoint, fractionalScale);
        System.out.println("// Copyright 2026 Marcelo Cantos");
        System.out.println("// SPDX-License-Identifier: Apache-2.0");
        System.out.println();
        System.out.println("// Generated by tools/PhysicalFontMetricsExtract.java using Java AWT");
        System.out.println("// fractional FontMetrics at 2048 points and exact 16.16 fixed units.");
        System.out.println("// Each maximal range contains assigned Unicode scalars with one");
        System.out.println("// identical tuple ordered");
        System.out.println("// as plain, bold, italic, bold-italic. Regenerate with:");
        System.out.println("//   java -Djava.awt.headless=true -cp /tmp/rustuml-font-extract \\");
        System.out.printf("//     PhysicalFontMetricsExtract \"%s\" --rust-unicode-ranges%n", family);
        System.out.println();
        System.out.printf(
            "const MISSING_FIXED_UNITS: [u32; 4] = [%d, %d, %d, %d];%n",
            missingUnits[0], missingUnits[1], missingUnits[2], missingUnits[3]);
        System.out.println();
        System.out.println("const UNICODE_RANGES: &[(u32, u32, [u32; 4])] = &[");

        int runStart = -1;
        int runEnd = -1;
        long[] runUnits = null;
        for (int codepoint = 128; codepoint <= Character.MAX_CODE_POINT; codepoint++) {
            if (!Character.isValidCodePoint(codepoint)
                || (codepoint >= Character.MIN_SURROGATE
                    && codepoint <= Character.MAX_SURROGATE)
                || !Character.isDefined(codepoint)) {
                continue;
            }
            long[] units = scalarFixedUnits(metrics, codepoint, fractionalScale);
            if (runStart >= 0
                && codepoint == runEnd + 1
                && Arrays.equals(runUnits, units)) {
                runEnd = codepoint;
                continue;
            }
            if (runStart >= 0) {
                printRustRange(runStart, runEnd, runUnits);
            }
            runStart = codepoint;
            runEnd = codepoint;
            runUnits = units;
        }
        if (runStart >= 0) {
            printRustRange(runStart, runEnd, runUnits);
        }
        System.out.println("];");
        System.out.println();
        System.out.println("pub(crate) fn fixed_units(codepoint: u32, bold: bool, italic: bool) -> u32 {");
        System.out.println("    let face = match (bold, italic) {");
        System.out.println("        (false, false) => 0,");
        System.out.println("        (true, false) => 1,");
        System.out.println("        (false, true) => 2,");
        System.out.println("        (true, true) => 3,");
        System.out.println("    };");
        System.out.println("    let index = UNICODE_RANGES.partition_point(|(start, _, _)| *start <= codepoint);");
        System.out.println("    if index > 0 {");
        System.out.println("        let (start, end, values) = UNICODE_RANGES[index - 1];");
        System.out.println("        if codepoint >= start && codepoint <= end {");
        System.out.println("            return values[face];");
        System.out.println("        }");
        System.out.println("    }");
        System.out.println("    MISSING_FIXED_UNITS[face]");
        System.out.println("}");
        graphics.dispose();
    }

    static long[] scalarFixedUnits(
        FontMetrics[] metrics,
        int codepoint,
        long fractionalScale
    ) {
        String text = new String(Character.toChars(codepoint));
        long[] result = new long[metrics.length];
        for (int i = 0; i < metrics.length; i++) {
            double units = metrics[i].getFont().getStringBounds(
                text, metrics[i].getFontRenderContext()).getWidth();
            double scaled = units * fractionalScale;
            if (scaled != Math.rint(scaled)) {
                throw new IllegalStateException(
                    String.format(
                        "advance %.15f for U+%X is not exact at scale %d",
                        units, codepoint, fractionalScale));
            }
            long fixed = Math.round(scaled);
            if (fixed < 0 || fixed > 0xFFFF_FFFFL) {
                throw new IllegalStateException(
                    String.format("advance %d for U+%X does not fit u32", fixed, codepoint));
            }
            result[i] = fixed;
        }
        return result;
    }

    static void printRustRange(int start, int end, long[] units) {
        System.out.printf(
            "    (0x%X, 0x%X, [%d, %d, %d, %d]),%n",
            start, end, units[0], units[1], units[2], units[3]);
    }

    static String repr(double value) {
        return Double.toString(value);
    }
}
