@startuml
skinparam Padding 0
class PadTreePairNorth9811
class PadTreePairSouth9813
PadTreePairNorth9811 --> PadTreePairSouth9813
note top on link
  |_ root 9811
  |__ branch 9813
  |___ leaf 9819
end note
@enduml
