@startuml
skinparam classBackgroundColor #F0F8FF
skinparam classBorderColor #003366
skinparam classHeaderBackgroundColor #003366
skinparam classFontColor #003366
skinparam classArrowColor #003366
skinparam roundCorner 10

class Animal {
  +name: String
  +getName(): String
}
class Dog extends Animal {
  +bark(): void
}
Animal <|-- Dog
@enduml
