@startuml
skinparam backgroundColor #FFF5E4
skinparam classBackgroundColor #FFE3E1
skinparam classBorderColor #FF9B9B
skinparam sequenceParticipantBackgroundColor #FFE3E1
skinparam sequenceParticipantBorderColor #FF9B9B
skinparam noteBackgroundColor #FFF5E4
skinparam noteBorderColor #FF9B9B

class Animal {
  +name: String
  +getName(): String
}
class Dog extends Animal {
  +bark(): void
}
Animal <|-- Dog
@enduml
