@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Courier
skinparam defaultFontSize 12

Alice -> Bob : request
Bob --> Alice : response
note right : note
@enduml
