@startuml
skinparam defaultFontSize 18
skinparam defaultFontStyle bold
skinparam classHeaderBackgroundColor LightBlue
skinparam roundCorner 15

Alice -> Bob : request
Bob --> Alice : response
note right : note
@enduml
