@startuml
skinparam classBackgroundColor #F0F8FF
skinparam classBorderColor #003366
skinparam classHeaderBackgroundColor #003366
skinparam classFontColor #003366
skinparam classArrowColor #003366
skinparam roundCorner 10

Alice -> Bob : request
Bob --> Alice : response
note right : note
@enduml
