@startuml
skinparam classRoundCorner 0
class Animal {{
  -name: String
  +getName(): String
  +setName(n: String): void
}}
class Dog extends Animal {{
  +bark(): void
}}
interface Flyable {{
  +fly(): void
}}
Animal <|-- Dog
Dog ..|> Flyable
@enduml
