@startjson
{
  "items": [
    "item_01", "item_02", "item_03", "item_04", "item_05",
    "item_06", "item_07", "item_08", "item_09", "item_10",
    "item_11", "item_12", "item_13", "item_14", "item_15"
  ]
}
@endjson
