@startyaml
app:
  name: MyService
  version: 2.0.0
  debug: false
database:
  host: localhost
  port: 5432
  credentials:
    user: admin
    password: secret
logging:
  level: info
  file: /var/log/app.log
@endyaml
