@startuml
skinparam nodesep 83.5
skinparam ranksep 67px

state LexicalAster {
  [*] --> LexicalAsterNorth
  LexicalAsterNorth --> LexicalAsterSouth
  LexicalAsterSouth --> [*]
}

state LexicalBirch {
  [*] --> LexicalBirchNorth
  LexicalBirchNorth --> LexicalBirchSouth
  LexicalBirchSouth --> [*]
}

[*] --> LexicalAster
[*] --> LexicalBirch
LexicalAster --> LexicalTerminus
LexicalBirch --> LexicalTerminus
LexicalTerminus --> [*]
@enduml
