@startuml
class Root
class L1A
class L1B
class L2A
class L2B
class L2C
class L2D
class L3A
class L3B
class L3C
Root <|-- L1A
Root <|-- L1B
L1A <|-- L2A
L1A <|-- L2B
L1B <|-- L2C
L1B <|-- L2D
L2A <|-- L3A
L2B <|-- L3B
L2C <|-- L3C

@enduml
