@startuml
left to right direction
skinparam nodesep 20
skinparam ranksep 40
class M0
class M1
class M2
class M3
class M4
class M5
class M6
class M7
class M8
class M9
class M10
class M11
class M12
class M13
class M14
M0 --> M1
M1 --> M2
M2 --> M3
M3 --> M4
M4 --> M5
M5 --> M6
M6 --> M7
M7 --> M8
M8 --> M9
M9 --> M10
M10 --> M11
M11 --> M12
M12 --> M13
M13 --> M14
@enduml
