@startuml
class Root
class A1
class A2
class A3
class A4
class A5
class A6
class A7
class A8
class A9
class A10
Root <|-- A1
Root <|-- A2
Root <|-- A3
Root <|-- A4
Root <|-- A5
Root <|-- A6
Root <|-- A7
Root <|-- A8
Root <|-- A9
Root <|-- A10

@enduml
