@startuml
class S0
class S1
class S2
class S3
class S4
class S5
class S6
class S7
class S8
class S9
class S10
class S11
class S12
class S13
class S14
class S15
class S16
class S17
class S18
class S19
class Hub
Hub --> S0
Hub --> S1
Hub --> S2
Hub --> S3
Hub --> S4
Hub --> S5
Hub --> S6
Hub --> S7
Hub --> S8
Hub --> S9
Hub --> S10
Hub --> S11
Hub --> S12
Hub --> S13
Hub --> S14
Hub --> S15
Hub --> S16
Hub --> S17
Hub --> S18
Hub --> S19
@enduml
