@startuml
class Item0
class Item1
class Item2
class Item3
class Item4
class Item5
class Item6
class Item7
class Item8
class Item9
class Item10
class Item11
class Item12
class Item13
class Item14
class Item15
class Item16
class Item17
class Item18
class Item19
class Item20
class Item21
class Item22
class Item23
class Item24
class Item25
class Item26
class Item27
class Item28
class Item29
class Item30
class Item31
class Item32
class Item33
class Item34
class Item35
class Item36
class Item37
class Item38
class Item39
class Item40
class Item41
class Item42
class Item43
class Item44
class Item45
class Item46
class Item47
class Item48
class Item49
Item0 <|-- Item1
Item1 <|-- Item2
Item2 <|-- Item3
Item3 <|-- Item4
Item4 <|-- Item5
Item5 <|-- Item6
Item6 <|-- Item7
Item7 <|-- Item8
Item8 <|-- Item9
Item9 <|-- Item10
Item10 <|-- Item11
Item11 <|-- Item12
Item12 <|-- Item13
Item13 <|-- Item14
Item14 <|-- Item15
Item15 <|-- Item16
Item16 <|-- Item17
Item17 <|-- Item18
Item18 <|-- Item19
Item19 <|-- Item20
Item20 <|-- Item21
Item21 <|-- Item22
Item22 <|-- Item23
Item23 <|-- Item24
Item24 <|-- Item25
Item25 <|-- Item26
Item26 <|-- Item27
Item27 <|-- Item28
Item28 <|-- Item29
Item29 <|-- Item30
Item30 <|-- Item31
Item31 <|-- Item32
Item32 <|-- Item33
Item33 <|-- Item34
Item34 <|-- Item35
Item35 <|-- Item36
Item36 <|-- Item37
Item37 <|-- Item38
Item38 <|-- Item39
Item39 <|-- Item40
Item40 <|-- Item41
Item41 <|-- Item42
Item42 <|-- Item43
Item43 <|-- Item44
Item44 <|-- Item45
Item45 <|-- Item46
Item46 <|-- Item47
Item47 <|-- Item48
Item48 <|-- Item49
@enduml
