!define SERVER_URL http://api.example.com
!define API_VERSION v2

@startuml
note : Server: SERVER_URL/API_VERSION
Alice -> Bob : Request
@enduml

@startuml
note : Also SERVER_URL/API_VERSION
Carol -> Dave : Another request
@enduml
